categorias(["Accion", "Rpg", "Aventura", "Casuales", "Indies", "Carreras", "Simulacion", "Deportes", "Rogue Like", "Plataformas", "Puzle", "Cartas", "Sandbox", "Bullet Hell", "Construccion", "Ciencia Ficcion", "Pixelados", "Exploracion", "Por Turnos", "Gestion", "Shooter", "Habilidad", "Estrategia", "Mundo Abierto", "Multijugador", "Viaje en el Tiempo", "Sigilo", "Narrativa", "Fantasia", "Fantasia Oscura", "Supervivencia", "Coleccion de Criaturas", "Survival Horror", "Estrategia en Tiempo Real", "Lucha", "ETR", "Construccion De Bases", "Terror", "Zombis", "Elecciones", "Metroidvaina", "Clicker", "Clasico", "Divertido", "Conversacion"]).
juego('Dark Souls', ["Accion", "Rpg", "Aventura"], 'https://store.steampowered.com/app/570940/DARK_SOULS_REMASTERED/', 'https://i.imgur.com/EiUHvbL.jpg', 'Dark Souls es el nuevo juego de rol y accion de los creadores de Demons Souls, FromSoftware. Dark Souls cuenta con muchos elementos ya conocidos: un universo fantastico y oscuro, tortuosos recorridos por mazmorras, temibles enemigos e interacciones online exclusivas. Sin embargo, Dark Souls es el sucesor espiritual de Demons Souls, no una secuela. Preparate para un nuevo mundo que induce a ladesesperacion, provisto de un amplio horizonte totalmente explorable y de relieves geograficos dispuestos en vertical. Preparate para una historia nueva y misteriosa que giraen torno al mundo de Lodran. Y, sobre todo, preparate para morir. Te enfrentaras a innumerables trampas mortales, a incontables hordas oscuras y grotescas y a varios jefesdemonios y dragones descomunales de una fuerza impresionante. Tendras que aprender de la muerte para sobrevivir en este mundo implacable', 'FromSoftware', ["Dificil", "SoulsLike", "Superacion", "Satisfactorio", "Rodar"]).
juego('Hades', ["Accion", "Indies", "Rogue Like"], 'https://store.steampowered.com/app/400/Portal/', 'https://i.imgur.com/7ctGXDY.jpg', 'Desafia al dios de los muertos, Hades, y protagoniza comoZagreus una salvaje fuga del Inframundo con el objetivo de descubrir secretos de tu pasado.', 'Supergiant Games', ["Mitologica", "Dificil", "Superacion", "Buena Historia"]).
juego('Portal', ["Puzle", "Ciencia Ficcion", "Accion"], 'https://store.steampowered.com/app/400/Portal/', 'https://i.imgur.com/gQI8Hwg.jpg', 'Un sujeto de prueba se despierta en una instalacion cientifica controlada por una inteligencia artificial sadica y debe escapar con la ayuda del unico instrumento que tiene: una pistola que hace portales dimensionales.', 'Valve', ["Chistes", "Revolucionario"]).
juego('Stardew Valley', ["Sandbox", "Simulacion", "Gestion"], 'https://store.steampowered.com/app/1145360/Hades/', 'https://i.imgur.com/qOEm09p.jpg', 'Stardew Valley es un juego de simulacion de granja inspirado en juegos como Harvest Moon. Al principio del juego, el jugador crea su personaje, pudiendo elegir el sexo del mismo, color y tipo de cabello, entre otros. El jugador recibela granja en ruinas que alguna vez poseyo su abuelo.', 'Eric Barone', ["Animales", "Vegetales", "Granja", "Chill", "Tranquilidad"]).
juego('The Binding of Isaac', ["Indies", "Rogue Like", "Accion"], 'https://store.steampowered.com/app/250900/The_Binding_of_Isaac_Rebirth/', 'https://i.imgur.com/DS7SoGb.jpg', 'En el transcurso del viaje de un chico llamado Isaac, que tras los incontables abusos de su madre religiosa emprende un viaje por su sotano, en el cual los jugadores encontraran extranos tesoros  que cambiaran la forma de Isaac, le daran habilidades y poderes sobrehumanos que le permitiran luchar  contra hordas de criaturas aterradoras y diabolicas, descubrir secretos y abrirse camino a su supervivencia.', 'Edmund McMillen', ["Religion", "Humor Negro", "Satiras", "Items", "Runs"]).
juego('Dead Cells', ["Metroidvaina", "Rogue Like", "Accion"], 'https://store.steampowered.com/app/588650/Dead_Cells/', 'https://i.imgur.com/yP9TkXr.png', 'Dead Cells es un videojuego de accion y plataformas en 2D con mapas muy grandes, en los que los jugadores podran perderse y explorar a placer, encontrando secretos, nuevas armas, artefactos y habilidades con las que  mejorar a nuestro personaje.', 'Motion Twin', ["Dificil", "Items", "Runs"]).
juego('Hotline Miami', ["Accion", "Indies", "Pixelados"], 'https://store.steampowered.com/app/219150/Hotline_Miami/', 'https://i.imgur.com/Ahzr2SG.jpg', 'Ambientado en un Miami alternativo de 1989, asumiras el papel de un antiheroe misterioso en un alboroto asesino contra el inframundo turbio a instancias de las voces en tu contestador automatico. Pronto te encontraras luchando  por entender lo que esta pasando y por que eres propenso a estos actos de violencia.', 'Devolver Digital', ["Sangriento", "Buena Musica", "Ritmico"]).
juego('Terraria', ["Sandbox", "Aventura", "Pixelados"], 'https://store.steampowered.com/app/105600/Terraria/', 'https://i.imgur.com/Xho4Wrf.jpg', 'Terraria es un videojuego de mundo abierto en 2D. Contiene elementos de construccion, exploracion, aventura y combate, muy similar a juegos clasicos de la consola Super NES, como por ejemplo la serie Metroid, y a otras entregas  no tan antiguas como Minecraft. El juego comienza en un mundo creado de forma aleatoria.', 'Re-Logic', ["Bloques", "Farmear", "Crear Mundo", "Crear Base"]).
juego('Minecraft', ["Sandbox", "Construccion", "Aventura"], 'https://www.minecraft.net/es-es/store/minecraft-deluxe-collection-pc', 'https://i.imgur.com/1GOsMUt.jpg', 'Minecraft es un videojuego tipo sandbox, su traduccion literal seria caja de arena y es lo que representa la experiencia de juego. Los jugadores pueden modelar el mundo a su gusto, destruir y construir, como si  estuviesen jugando en una caja de arena.', 'Mojang', ["Bloques", "Revolucionario", "Farmear", "Tecnico"]).
juego('Brotato', ["Rogue Like", "Bullet Hell", "Accion"], 'https://store.steampowered.com/app/1942280/Brotato/', 'https://i.imgur.com/iRp1Iqh.jpg', 'Brotato es un roguelite de disparos en el que te moveras de arriba abajo del escenario. Encarna a una patata con 6 armas simultaneas para hacer frente a los alienigenas. Elige entre una variedad de caracteristicas y objetos para  crear combinaciones unicas y sobrevivir hasta que acudan los refuerzos.', 'Blobfish', ["Dificil", "Runs", "Items"]).
juego('Downwell', ["Rogue Like", "Plataformas", "Indies"], 'https://store.steampowered.com/app/360740/Downwell/', 'https://i.imgur.com/DitNFHD.jpg', 'Downwell es un curioso juego sobre un joven que se aventura en un pozo en busca de tesoros olvidados con la unica ayuda de sus botas-pistola para protegerse. Abrete camino entre la oscuridad habitada por temibles criaturas y  misteriosos secretos para conseguir las espectaculares gemas rojas repartidas por las rocas.', 'Moppin', ["Dificil", "Runs", "Items", "Estetico"]).
juego('Bastion', ["Rpg", "Accion", "Indies"], 'https://store.steampowered.com/app/107100/Bastion/', 'https://i.imgur.com/jOcjQBA.jpg', 'Bastion es un juego bidimensional que utiliza un punto de vista isometrico y cuenta con una narracion dinamica que interactua con el personaje mientras este avanza. El juego fue desarrollado en un periodo de dos anos por un equipo de siete personas divididas entre las ciudades de San Jose y Nueva York.', 'Supergiant Games', ["Dificil", "Superacion", "Buena Historia", "Rodar"]).
juego('Enter the Gungeon', ["Rogue Like", "Bullet Hell", "Accion"], 'https://store.steampowered.com/app/311690/Enter_the_Gungeon/', 'https://i.imgur.com/HhNYvcy.jpg', 'Enter the Gungeon es un dungeon crawler de tiroteos que sigue a una banda de marginados arrepentidos en su intento de conseguir la absolucion personal a base de disparar, saquear, dar volteretas y voltear mesas para alcanzar el tesoro supremo de la legendaria Armazmorra: el arma que puede matar el pasado.', 'Devolver Digital', ["Dificil", "Superacion", "Buena Historia", "Rodar", "Runs", "Items"]).
juego('Kenshi', ["Rpg", "Sandbox", "Construccion"], 'https://store.steampowered.com/app/233860/Kenshi/', 'https://i.imgur.com/tmhXMXz.jpg', 'Kenshi es un juego de rol multijugador y supervivencia en un gigantesco mundo abierto. En Kenshi, los jugadores encontraran elementos tipicos del genero del rol, asi como la posibilidad de construir ciudades y fortalezas. El titulo tiene lugar en un mundo de canibales, criaturas extranas y duras condiciones climaticas.', 'Lo-Fi Games', ["Dificil", "Tecnico", "Crear Base"]).
juego('Game Dev Tycoon', ["Simulacion", "Indies", "Gestion"], 'https://store.steampowered.com/app/239820/Game_Dev_Tycoon/', 'https://i.imgur.com/nYK9Nh1.jpg', 'In Game Dev Tycoon you replay the history of the gaming industry by starting your own video game development company in the 80s. Create best selling games. Research new technologies and invent new game types. Become the leader of the market and gain worldwide fans.', 'Greenheart Games', ["Juegos", "Chill", "Tranquilidad"]).
juego('Sekiro', ["Accion", "Rpg", "Aventura"], 'https://store.steampowered.com/app/814380/Sekiro_Shadows_Die_Twice__GOTY_Edition/', 'https://i.imgur.com/88YIWxc.jpg', 'Sekiro: Shadows Die Twice es un videojuego de accion-aventura desarrollado por FromSoftware y publicado por Activision. Dirigido por Hidetaka Miyazaki; se estreno el 22 de marzo de 2019 para PlayStation 4, Xbox One y Microsoft  Windows. Su historia la protagoniza un shinobi llamado Sekiro durante el periodo Sengoku, cuya intencion es la de vengarse de un samurai que le ataco y secuestro a su senor.', 'FromSoftware', ["Dificil", "SoulsLike", "Superacion", "Satisfactorio", "Rodar"]).
juego('Transistor', ["Indies", "Rpg", "Accion"], 'https://store.steampowered.com/app/237930/Transistor/', 'https://i.imgur.com/gUOwqQT.jpg', 'Transistor, de los creadores de Bastion, es un juego de rol con tematica de ciencia ficcion que te invita a blandir un arma extraordinaria de origen desconocido para luchar a lo largo y ancho de una espectacular ciudad futurista. En el  mismo se utiliza mucho las tematicas de la programacion para los mecanismos de combates', 'Supergiant Games', ["Futurista", "Dificil", "Superacion", "Buena Historia", "Revolucionario", "Programacion"]).
juego('Spore', ["Sandbox", "Simulacion", "Exploracion"], 'https://store.steampowered.com/app/17390/SPORE/', 'https://i.imgur.com/gWbxtWj.jpg', 'Spore es un videojuego de simulacion de vida y estrategia para Apple Macintosh y Microsoft Windows desarrollado por Maxis y disenado por Will Wright que simula la evolucion de una especie desde las etapas  mas primitivas es decir seres unicelulares, hasta la colonizacion de la galaxia por parte del ser evolucionado.', 'Electronic Arts', ["Especies", "Civilizacion", "Evolucion"]).
juego('Darkest Dungeon', ["Rpg", "Rogue Like", "Por Turnos"], 'https://store.steampowered.com/app/262060/Darkest_Dungeon/', 'https://i.imgur.com/zr4axCf.jpg', 'Darkest Dungeon es un desafiante juego de rol gotico en mazmorras y por turnos que gira en torno al esfuerzo psicologico de la aventura. Recluta, entrena y lidera a un equipo de heroes imperfectos a traves  de enrevesados bosques, laberintos olvidados, criptas en ruinas y mas alla.', 'Red Hook Studios', ["Dificil", "Tactico", "Runs", "Items", "Sangriento"]).
juego('Wizard Legend', ["Rogue Like", "Indies", "Bullet Hell"], 'https://store.steampowered.com/app/445980/Wizard_of_Legend/', 'https://i.imgur.com/fWwIGwS.jpg', 'Wizard of Legend es un juego de mazmorras vertiginoso que pone el acento en los combates magicos dinamicos. Los rapidos movimientos y uso de la magia aun mas rapido te permitiran encadenar hechizos para realizar  combinaciones devastadoras contra tus enemigos.', 'Humble Games', ["Dificil", "Magos", "Superacion", "Hechizos", "Rodar"]).
juego('Forager', ["Indies", "Sandbox", "Casuales"], 'https://store.steampowered.com/app/751780/Forager/', 'https://i.imgur.com/jvPMzdp.jpg', 'Forager es un videojuego de accion, exploracion, artesania y agricultura, mas una pizca de combate. Encarnaremos a un simpatico un personaje que esta en una isla solitaria, acompanados de un pico, algunos arboles y rocas, y que gracias a  su ingenio, debera sobrevivir y seguir adelante. Ademas es argentino papa.', 'Humble Games', ["Animales", "Vegetales", "Granja", "Chill", "Tranquilidad"]).
juego('Furi', ["Bullet Hell", "Accion", "Ciencia Ficcion"], 'https://store.steampowered.com/app/423230/Furi/', 'https://i.imgur.com/PI95iTP.jpg', 'Furi es un juego de accion beatem up que nos propone acabar con la vida de un variado grupo de enemigos finales. El juego apuesta por un sistema de combate inspirado por los clasicos japoneses. Utiliza la mecanica de solo combates contra jefes y buscar tener una dificultad elevada.', 'The Game Bakers', ["Dificil", "Superacion", "Buena Historia", "Rodar"]).
juego('Planet Zoo', ["Simulacion", "Gestion", "Construccion"], 'https://store.steampowered.com/app/703080/Planet_Zoo/', 'https://i.imgur.com/G1T1x5A.jpg', 'Ambientandose en un enorme zoo, los jugadores tendran que gestionar pequenos ecosistemas para cada una de las especies de animales dentro del parque, mejorandolos poco a poco modificando el terreno y anadiendo juguetes y  atracciones para que los animales se diviertan y aprendan.', 'Frontier Developments', ["Animales", "Zoologico", "Chill", "Tranquilidad"]).
juego('Pyre', ["Indies", "Deportes", "Rpg"], 'https://store.steampowered.com/app/462770/Pyre/', 'https://i.imgur.com/wObjrXC.jpg', 'Pyre es un Rpg por equipos en el que intentaras conducir a la libertad a una banda de exiliados alcanzando la victoria en las ancestrales competiciones que se libran en un vasto y mistico purgatorio. Quien regresara entre laureles y quien pasara el  resto de sus dias condenado al exilio?', 'Supergiant Games', ["Pelota", "Dificil", "Superacion", "Buena Historia"]).
juego('Children of Morta', ["Rogue Like", "Accion", "Indies"], 'https://store.steampowered.com/app/330020/Children_of_Morta/', 'https://i.imgur.com/CgIQpH2.jpg', 'Children of Morta es un juego de Rpg de accion historial sobre una familia extraordinaria de heroes. Dirige a los Bergson, con todos sus defectos y virtudes, contra la proxima corrupcion. Seras capaz de sacrificar todo para salvar a los que te importan?', '11 bit studios', ["Buena Historia", "Rodar", "Magia", "Hechizos", "Runs"]).
juego('Graveyard Keeper', ["Indies", "Sandbox", "Gestion"], 'https://store.steampowered.com/app/599140/Graveyard_Keeper/', 'https://i.imgur.com/4B7UP8k.jpg', 'Graveyard Keeper es el simulador de gestion de cementerios medievales mas impreciso de la historia. Construye y gestiona tu propio cementerio mientras encuentras formas de reducir costes, meterte en otras empresas y usar todos los recursos que encuentres.', 'tinyBuild', ["Animales", "Vegetales", "Granja", "Chill", "Tranquilidad", "Cementerio"]).
juego('Hand of Fate 2', ["Cartas", "Rogue Like", "Indies"], 'https://store.steampowered.com/app/456670/Hand_of_Fate_2/', 'https://i.imgur.com/Zy28Naw.jpg', 'Hand Of Fate 2 es un juego de exploracion de mazmorras ambientado en un mundo de oscura fantasia. Domina un juego de mesa rebosante de vida en el que cada fase de la aventura se saca de una baraja de encuentros legendarios que tu te encargas de elegir.', 'Defiant Development', ["Juego de Mesa", "calabozos y dragones"]).
juego('Have a Nice Death', ["Rogue Like", "Plataformas", "Accion"], 'https://store.steampowered.com/app/1740720/Have_a_Nice_Death/', 'https://i.imgur.com/EPWMKAO.jpg', 'Have a Nice Death es un roguelike de accion en el que encarnas a una Parca saturada por el trabajo. Sus empleados estan echando por tierra tanto el equilibrio de las almas. Con el fin de recuperar el orden, tendras que servirte de tu guadana para demostrar a los empleados quien manda aqui.', 'Gearbox Publishing', ["Estetico", "Buena Historia", "Humor Negro", "Satiras", "Items", "Runs"]).
juego('Back To Bed', ["Puzle", "Indies", "Casuales"], 'https://store.steampowered.com/app/308040/Back_to_Bed/', 'https://i.imgur.com/hey8j52.jpg', 'Back to Bed es un juego indie de rompecabezas en 3D ambientado en un mundo de suenos unico, hermoso y artistico, en el que guias al sonambulo Bob a la seguridad de su cama. Para lograr esto, debes tomar el control del guardian subconsciente de Bob llamado Subob.', 'Bedtime Digital Games', ["Raro", "Para Pensar", "Estetico"]).
juego('Nioh', ["Rpg", "Accion", "Aventura"], 'https://store.steampowered.com/app/485510/Nioh_Complete_Edition/', 'https://i.imgur.com/CXRBRh5.jpg', 'La aventura se ambienta en el Japon feudal y cuenta con la presencia de multitud de demonios y seres sobrenaturales del folclore de dicho pais. Su estilo de lucha y combate sera arido y dificil, invitando al jugador a prepararse concienzudamente en cada enfrentamiento.', 'KOEI TECMO', ["Dificil", "SoulsLike", "Superacion", "Satisfactorio", "Rodar"]).
juego('Titan Souls', ["Indies", "Bullet Hell", "Pixelados"], 'https://store.steampowered.com/app/297130/Titan_Souls/', 'https://i.imgur.com/yeC5sMM.jpg', 'El objetivo consiste en derrotar a los veinte monstruos gigantes (veintiuno en modo dificil) conocidos como los Titanes, los cuales, al igual que el jugador, solo pueden recibir un golpe pero solo tienen una forma de ser derrotados.', 'Devolver Digital', ["Dificil", "Un Golpe", "Items", "Runs"]).
juego('Zoo Tycoon', ["Simulacion", "Gestion", "Construccion"], 'https://store.steampowered.com/app/613880/Zoo_Tycoon_Ultimate_Animal_Collection/', 'https://i.imgur.com/qGQ9mbQ.jpg', 'En Zoo Tycoon tenemos que crear y gestionar un zoo, asegurandonos de que los animales sean felices, teniendo cubiertas sus necesidades basicas, lo que atraera a visitantes al zoo, a los que tambien tendremos que tener contentos con una fauna variada, servicios basicos como cafeterias, tiendas de recuerdos, etc.', 'Frontier Developments', ["Animales", "Zoologico", "Chill", "Tranquilidad"]).
juego('Super Meat Boy Forever', ["Plataformas", "Indies", "Pixelados"], 'https://store.steampowered.com/app/581660/Super_Meat_Boy_Forever/', 'https://i.imgur.com/pmdIEWk.jpg', 'Super Meat Boy Forever es una nueva entrega del famoso titulo de plataformas y accion. En este juego, Meat Boy y Bandage Girl han tenido una hija, Nugget, pero sus pacificas vidas familiares se veran interrumpidas cuando el Dr. Fetus regrese para secuestrar a la pequena Nugget.', 'Edmund McMillen', ["Sangriento", "Humor Negro", "Dificil"]).
juego('Super Meat Boy', ["Plataformas", "Indies", "Pixelados"], 'https://store.steampowered.com/app/40800/Super_Meat_Boy/', 'https://i.imgur.com/LT836o9.jpg', 'Super Meat Boy es un juego de plataformas extremadamente dificil en el que juegas en la piel de un cubo de carne animado que intenta salvar a su novia (que esta hecha de vendajes) de un malvado feto en un tarro que viste de esmoquin.', 'Edmund McMillen', ["Sangriento", "Humor Negro", "Dificil"]).
juego('The Witcher 3 Wild Hunt', ["Rpg", "Accion", "Aventura"], 'https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/', 'https://i.imgur.com/lVFVLp0.jpg', 'Es un juego de perspectiva en tercera persona, el jugador controla al protagonista Geralt de Rivia, un cazador de monstruos conocido como Lobo Blanco, es un brujo, el cual emprende un largo viaje a traves de Los reinos del norte.', 'CD PROJEKT RED', ["Magia", "Hechizos", "Buena Historia"]).
juego('Tetris', ["Puzle", "Habilidad", "Estrategia"], 'https://store.steampowered.com/app/1003590/Tetris_Effect_Connected/', 'https://i.imgur.com/yyScbFv.jpg', 'El objetivo es hacer caer piezas e ir rellenando huecos para conseguir hacer lineas. Una vez creadas, desaparecen, y nos interesa hacerlo de cuatro en cuatro en vez de una en una por los puntos que hay implicados en ello. Si consigues una de cuatro, felicidades, acabas de hacer un Tetris.', 'Aleksei Pazhitnov', ["Retro", "Chill"]).
juego('The Elder Scrolls V Skyrim', ["Rpg", "Accion", "Mundo Abierto"], 'https://store.steampowered.com/app/489830/The_Elder_Scrolls_V_Skyrim_Special_Edition/', 'https://i.imgur.com/yvmAXgb.jpg', 'La historia de Skyrim se centra en los esfuerzos del personaje, Dovahkiin (sangre de dragon), para derrotar a Alduin, un dragon/dovah que, segun la profecia, destruira el mundo. La trama esta fechada doscientos anos despues de los sucesos de Oblivion y tiene lugar en la provincia ficticia de Skyrim.', 'Bethesda', ["Magia", "Hechizos", "Buena Historia"]).
juego('Red Dead Redemption 2', ["Accion", "Aventura", "Mundo Abierto"], 'https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/', 'https://i.imgur.com/e8cBENL.jpg', 'Despues de que un atraco en el pueblo de Blackwater sale muy mal, Arthur Morgan y la banda Van der Linde se ven obligados a huirse. Con agentes federales y los mejores cazarrecompensas persiguiendolos, la banda debe robar, atracar y luchar por el duro corazon de Estados Unidos para sobrevivir.', 'Rockstar Games', ["Buena Historia", "Historico", "Cowboys", "Pistolas", "Sangriento", "Tiros"]).
juego('Grand Theft Auto V', ["Accion", "Mundo Abierto", "Aventura"], 'https://store.steampowered.com/app/271590/Grand_Theft_Auto_V/', 'https://i.imgur.com/JhAlldL.jpg', 'Se trata de una aventura de accion de mundo abierto con multitud de misiones en la que encarnamos a tres personajes distintos: Trevor, Michael y Franklin. Ademas, cuenta con GTA Online, el modo multijugador en linea de GTA 5.', 'Rockstar Games', ["Buena Historia", "Robos", "Pistolas", "Sangriento", "Libertad", "Tiros"]).
juego('Halo Combat Evolved', ["ETR", "Estrategia", "Construccion De Bases"], 'https://store.steampowered.com/app/1064221/Halo_Combat_Evolved_Anniversary/', 'https://i.imgur.com/kMW8CEf.jpg', 'En esta guerra galactica el juego nos situa en una especie de asalto por parte del Pacto a una nave nodriza en la cual nuestro heroe, que se llama "Jefe Maestro", se prepara para el conflicto. El asalto finaliza con nuestro heroe en orbita hacia el mundo-anillo de Halo, donde tendra que salvaguardar la I.A.', 'Xbox Game Studios', ["Aliens", "Tactico", "Pistolas"]).
juego('Halo Wars Definitive Edition', ["Shooter", "Ciencia Ficcion", "Multijugador"], 'https://store.steampowered.com/app/459220/Halo_Wars_Definitive_Edition/', 'https://i.imgur.com/mz0h991.jpg', 'Halo Wars para Xbox One es un nuevo juego de estrategia en tiempo real basado en el universo Halo, continuacion directa del primer Halo Wars de Xbox 360. El titulo cuenta con dos bandos, los humanos de la UNSC y los Banished, una raza alienigena que sustituye al Covenant.', 'Xbox Game Studios', ["Tiros", "Pistolas", "Tecnologia", "Aliens"]).
juego('Halo The Master Chief Collection', ["Shooter", "Ciencia Ficcion", "Multijugador"], 'https://store.steampowered.com/app/976730/Halo_The_Master_Chief_Collection/', 'https://i.imgur.com/8yoS3GU.jpg', 'Halo es una franquicia de videojuegos de ciencia ficcion creada y desarrollada por Bungie Studios hasta Halo Reach, y gestionada ahora por 343 Industries, propiedad de Xbox Game Studios. La serie se centra en una guerra interestelar entre la humanidad y una alianza teocratica de alienigenas conocidos como Covenant.', 'Xbox Game Studios', ["Aliens", "Tiros", "Pistolas", "Tecnologia"]).
juego('Portal 2', ["Puzle", "Plataformas", "Accion"], 'https://store.steampowered.com/app/620/Portal_2/', 'https://i.imgur.com/JH5VbKC.jpg', 'Tras los eventos del primer Portal, Chell (nuestra protagonista) despierta 50 dias despues de haber sido criogenizada en una camara de relajacion, donde una maquina alternativa le da una serie de indicaciones para moverse y finalmente volver a dormir.', 'Valve', ["Chistes", "Revolucionario"]).
juego('Chrono Trigger', ["Rpg", "Viaje en el Tiempo", "Aventura"], 'https://store.steampowered.com/app/613830/CHRONO_TRIGGER/', 'https://i.imgur.com/RG5Xxeh.jpg', 'La historia del juego sigue a un grupo de jovenes aventureros que fueron transportados a traves del tiempo accidentalmente y descubrieron que el mundo iba a ser destruido en un futuro lejano. Jurando prevenir este desastre, viajan a traves de distintas epocas para descubrir la forma de salvar al planeta.', 'Square Enix', ["Retro", "Nostalgia"]).
juego('Metal Gear Solid Master Collection Vol1', ["Accion", "Sigilo", "Narrativa"], 'https://store.steampowered.com/app/2131630/METAL_GEAR_SOLID_MASTER_COLLECTION_Vol1_METAL_GEAR_SOLID/', 'https://i.imgur.com/nZK72cs.jpg', 'Metal Gear Solid es un videojuego de accion y sigilo firmado por Hideo Kojima y Konami para la consola PlayStation. Se trata de una secuela de Metal Gear y Metal Gear 2: Solid Snake. Descrito por su propio creador como "accion tactica de espionaje" en el titulo, la historia sigue la mision de Solid Snake, un soldado infiltrado en una instalacion de desarrollo de armas nucleares (Shadow Moses) para neutralizar un terrorista y salvar unos rehenes, entre ellos el jefe de DARPA.', 'KONAMI', ["Buena Historia", "Tiros", "Armas"]).
juego('Mass Effect', ["Rpg", "Ciencia Ficcion", "Accion"], 'https://store.steampowered.com/app/17460/Mass_Effect_2007/', 'https://i.imgur.com/3KhKfqC.jpg', 'Mass Effect es un videojuego de rol de accion y disparos en 3 persona de ciencia ficcion para Xbox 360, Microsoft Windows y posteriormente PlayStation 3, desarrollado por BioWare, famoso estudio desarrollador de juegos de rol como Jade Empire, Star Wars: Caballeros de la Antigua Republica.', 'Electronic Arts', ["Tiros", "Armas", "Aliens", "Pelicula"]).
juego('Bloodborne', ["Accion", "Rpg", "Fantasia Oscura"], 'No existe :c', 'https://i.imgur.com/oT7770U.jpg', 'Bloodborne nos lleva a la decrepita ciudad de Yharnam, cuyos habitantes han sido infectados por una misteriosa enfermedad sanguinea. Nosotros encarnamos al Cazador, un personaje que tendra que buscar una misteriosa sustancia llamada Sangre palida mientras resuelve misterios y se enfrenta a todo tipo de criaturas.','FromSoftware', ["Dificil", "SoulsLike", "Superacion", "Satisfactorio", "Rodar"]).
juego('Half Life', ["Shooter", "Ciencia Ficcion", "Accion"], 'https://store.steampowered.com/app/70/HalfLife/', 'https://i.imgur.com/ppxZwgW.jpg', 'Half-Life narra las aventuras de Gordon Freeman, un cientifico teorico del Laboratorio de Materiales Anomalos del Centro de Investigacion Black Mesa, un enorme complejo cientifico subterraneo y ultra secreto instalado en una base militar en desuso emplazada en el desierto de Nuevo Mexico.', 'Valve', ["Aliens", "Revolucionario", "Buenas Fisicas", "Armas", "Tiros"]).
juego('Half Life 2', ["Shooter", "Ciencia Ficcion", "Accion"], 'https://store.steampowered.com/app/220/HalfLife_2/', 'https://i.imgur.com/Tu2yhmv.jpg', 'Un shooter en primera persona que transcurre dos decadas despues de la historia del primer Half Life. Gordon Freeman despierta de su estado de hibernacion y se convierte en el simbolo de la resistencia humana frente a la Alianza. Accion en una aventura cuya historia profundiza mucho mas alla del conflicto.', 'Valve', ["Aliens", "Revolucionario", "Buenas Fisicas", "Armas", "Tiros"]).
juego('Half Life Alyx', ["Shooter", "Ciencia Ficcion", "Accion"], 'https://store.steampowered.com/app/546560/HalfLife_Alyx/', 'https://i.imgur.com/xJVItSy.jpg', 'Es la historia de una lucha imposible contra una raza alienigena cruel conocida como la Alianza, situada entre los eventos de Half-Life y Half-Life 2. Jugando como Alyx Vance, eres la unica oportunidad de supervivencia de la humanidad.', 'Valve', ["Aliens", "Revolucionario", "Buenas Fisicas", "Armas", "Tiros", "Realidad Virtual"]).
juego('Overwatch 2', ["Shooter", "Multijugador", "Accion"], 'https://store.steampowered.com/app/2357570/Overwatch_2/', 'https://i.imgur.com/LYyWLUY.jpg', 'Overwatch 2 es un juego gratuito de accion y disparos en equipos a cargo de Blizzard para PC, PlayStation 4, Xbox One, PlayStation 5, Xbox Series y Switch siempre activo y en constante evolucion que esta ambientado en un futuro optimista, donde en cada partida se viven intensas batallas de 5 vs. 5.', 'Blizzard', ["Tiros", "Armas", "Moba", "Online"]).
juego('Diablo II', ["Rpg", "Accion", "Fantasia"], 'https://diablo2.blizzard.com/es-es/', 'https://i.imgur.com/ky2MXSG.jpg', 'Diablo II: Resurrected es una version remasterizada del gran clasico de rol y accion Diablo II. Persigue al misterioso vagabundo oscuro y lucha contra los moradores del infierno mientras investigas el destino de los demonios mayores, Diablo, Mefisto y Baal, ahora hasta en 4K (2160p) en PC.', 'Blizzard', ["Magia", "Items", "Farmear", "Online"]).
juego('Resident Evil 3', ["Survival Horror", "Accion", "Zombis"], 'https://store.steampowered.com/app/952060/Resident_Evil_3/', 'https://i.imgur.com/8kUH9Ww.png', 'El 28 de septiembre de 1998, la exmiembro del Servicio Especial de Tacticas y Rescate (S.T.A.R.S.), Jill Valentine, es atacada en su departamento por una arma biologica inteligente conocida como Nemesis, que intenta matarla a ella y a todos los miembros restantes de S.T.A.R.S.', 'Capcom', ["Armas", "Tiros", "Retro", "Apocalipsis"]).
juego('Resident Evil 4', ["Survival Horror", "Accion", "Zombis"], 'https://store.steampowered.com/app/2050650/Resident_Evil_4/', 'https://i.imgur.com/wBFfh8r.jpg', 'Sigue la historia del sobreviviente Leon Scott Kennedy, ahora un agente de Estados Unidos al cual se le asigno la mision de rescatar a la hija del actual presidente del pais, Ashley Graham, quien habia sido raptada por un grupo terrorista desconocido.', 'Capcom', ["Armas", "Tiros", "Retro", "Apocalipsis"]).
juego('Resident Evil 7', ["Survival Horror", "Accion", "Terror"], 'https://store.steampowered.com/app/418370/Resident_Evil_7_Biohazard/', 'https://i.imgur.com/zNwBFA8.jpg', 'La historia gira alrededor de Ethan, el protagonista de la trama que decide ir a buscar a su desaparecida pareja, Mia, de la que no sabe nada desde hace mas de tres anos. Un misterioso correo electronico firmado a su nombre le indica la llegada a una casa regentada por la familia Baker.', 'Capcom', ["Armas", "Tiros", "Psicologico", "Apocalipsis"]).
juego('Fallout New Vegas', ["Rpg", "Mundo Abierto", "Accion"], 'https://store.steampowered.com/app/22380/Fallout_New_Vegas/', 'https://i.imgur.com/Si9csti.jpg', 'Fallout: New Vegas es un juego de rol de accion ambientado en un mundo postapocaliptico en el ano 2281. El jugador asume el papel de un mensajero que es dejado moribundo en el desierto de Mojave despues de ser atacado y robado de un paquete muy valioso.', 'Bethesda', ["Buena Historia", "Tiros", "Armas", "Humor Negro", "Apocalipsis"]).
juego('The Last of Us', ["Accion", "Aventura", "Supervivencia"], 'https://store.steampowered.com/app/1888930/The_Last_of_Us_Parte_I/', 'https://i.imgur.com/mSu6o5g.jpg', 'La trama describe las vivencias de Joel y Ellie, un par de supervivientes de una pandemia en Estados Unidos que provoca la mutacion de los seres humanos en criaturas canibales.', 'Naughty Dog', ["Buena Historia", "Tiros", "Armas", "Apocalipsis"]).
juego('StarCraft', ["Estrategia en Tiempo Real", "Ciencia Ficcion", "Multijugador"], 'https://us.shop.battle.net/es-es/product/starcraft-remastered', 'https://i.imgur.com/9gUX3I7.jpg', 'Comanda a los mecanizados terran, los psionicos protoss y los insectoides zerg en grandes batallas por el control de mapas en ocho entornos unicos. Construye tu base y recluta un ejercito en este juego de guerra en tiempo real ambientado en un futuro de ciencia ficcion.', 'Blizzard', ["Online", "Moba", "Tactico", "Dificil"]).
juego('OneShot', ["Pixelados", "Puzle", "Elecciones"], 'https://store.steampowered.com/app/420530/OneShot/', 'https://i.imgur.com/7enSggX.png', 'OneShot es un juego de aventuras y rompecabezas surrealista con perspectiva a vista de pajaro y una jugabilidad unica. Tienes que guiar a un nino a traves de un misterioso mundo en una mision para recuperar su sol, que murio hace mucho tiempo. El mundo sabe que existes.', 'KOMODO', ["Buena Historia", "Para Pensar", "Triste", "Sentimental"]).
juego('Monument Valley', ["Aventura", "Puzle", "Casuales"], 'https://store.steampowered.com/app/1927720/Monument_Valley_Panoramic_Edition/', 'https://i.imgur.com/kFvpWfx.jpg', 'En Monument Valley, debes manipular arquitecturas imposibles y guiar a una princesa silenciosa por un mundo de belleza incomparable. Monument Valley es un viaje irreal por construcciones fantasticas y geometrias imposibles.', 'ustwo games', ["Estetico", "Para Pensar", "Dificil"]).
juego('Left 4 Dead 2', ["Zombies", "Shooter", "Multijugador"], 'https://store.steampowered.com/app/550/Left_4_Dead_2/', 'https://i.imgur.com/1QRMlqX.jpg', 'Left 4 Dead 2 se desarrolla tres semanas despues del primer brote viral que se ha expandido en el sur de los Estados Unidos, infectando los territorios entre Georgia y Luisiana. La infeccion ya ha cobrado las vidas de millones de personas y sus mutaciones extraordinarias siguen apareciendo.', 'Valve', ["Armas", "Tiros", "Humor Negro", "Divertido"]).
juego('Hollow Knight', ["Metroidvaina", "Plataformas", "Accion"], 'https://store.steampowered.com/app/367520/Hollow_Knight/', 'https://i.imgur.com/VapaL3g.jpg', 'Hollow Knight es una aventura de accion clasica en 2D ambientada en un vasto mundo interconectado. Explora cavernas tortuosas, ciudades antiguas y paramos mortales. Combate contra criaturas corrompidas, haz nuevas amistades con extranos insectos y resuelve los antiguos misterios que yacen en el corazon del reino.', 'Team Cherry', ["Dificil", "Estetico", "Sentimental"]).
juego('Slay the Spire', ["Rogue Like", "Cartas", "Estrategia"], 'https://store.steampowered.com/app/646570/Slay_the_Spire/', 'https://i.imgur.com/IeIbx4c.jpg', 'Hemos fusionado juegos de cartas y roguelikes para crear el mejor juego de cartas para un solo jugador que pudieramos. Crea un mazo unico, encuentra criaturas extranas, descubre reliquias de inmenso poder y mata La Aguja.', 'Mega Crit Games', ["Tactico", "Runs", "Items"]).
juego('Slime Rancher', ["Aventura", "Gestion", "Casuales"], 'https://store.steampowered.com/app/433340/Slime_Rancher/', 'https://i.imgur.com/JX2lJh9.jpg', 'Juega como Beatrix LeBeau: una intrepida joven ranchera que se aventura a una vida a mil anos luz de la Tierra en la Lejana, Lejana Pradera. Cada dia presenta nuevos retos y riesgosas oportunidades mientras intentas amasar una gran fortuna en el negocio de la crianza de slimes.', 'Monomi Park', ["Slims", "Vegetales", "Granja", "Chill", "Tranquilidad", "Tierno"]).
juego('Papers Please', ["Indie", "Simulacion", "Elecciones"], 'https://store.steampowered.com/app/239030/Papers_Please/', 'https://i.imgur.com/yLSMWpV.jpg', 'Papers, Please tiene lugar en 1982 despues de una guerra de seis anos entre los estados ficticios de Arstotzka y Kolechia. La mecanica del juego se enfoca en la vida laboral de un inspector de inmigracion que trabaja para el gobierno de Arstotzka en un control fronterizo ubicado entre Arstotzka y Kolechia.', '3909', ["Buena Historia", "Tactico", "Sentimental"]).
juego('Cookie Clicker', ["Indie", "Clicker", "Casuales"], 'https://store.steampowered.com/app/1454400/Cookie_Clicker/', 'https://i.imgur.com/hqw7ZF5.png', 'Cookie Clicker es un emocionante juego de hacer clic que te da la bienvenida a un mundo cautivador. En este juego, tu objetivo final es reclamar el titulo de Cookie King, gobernando un reino de delicias deliciosas.', 'Playsaurus', ["Galletitas", "Chill", "Tranquilidad"]).
juego('Kingdom Rush', ["Indie", "Construccion De Bases", "Estrategia"], 'https://store.steampowered.com/app/246420/Kingdom_Rush___Tower_Defense/', 'https://i.imgur.com/jN0ZxRV.jpg', 'De que se trata? El reino esta bajo ataque. En Kingdom Rush debes defender tu reino contra hordas de trolls, orcos, demonios desagradables y trolls. Enfrentate a ellos con un grupo de guerreros y magos que defenderan su reino hasta el final.', 'Ironhide Game Studio', ["Tactico", "Chill", "Tranquilidad"]).
juego('Cuphead', ["Plataformas", "Indie", "Accion"], 'https://store.steampowered.com/app/268910/Cuphead/', 'https://i.imgur.com/8jvNSfB.jpg', 'Cuphead es un juego clasico de accion de disparos muy enfocado en batallas de jefes. Inspirado en las caricaturas de 1930, las imagenes y el audio se crearon de forma minuciosa con las mismas tecnicas de la era, esto es, animacion tradicional a mano, fondos de marca de agua y grabaciones originales de jazz.', 'Studio MDHR', ["Dificil", "Estetico", "Retro", "Revolucionario"]).
juego('God of War', ["Accion", "Aventura", "Rpg"], 'https://store.steampowered.com/app/1593500/God_of_War/', 'https://i.imgur.com/b9vuQGB.jpg', 'Tras haberse cobrado su venganza contra su padre Zeus y los demas Dioses Olimpicos, el antiguo dios de la guerra, Kratos, ahora vive con su joven hijo Atreus en el mundo de los Dioses Nordicos, una tierra hostil habitada por feroces monstruos y guerreros.', 'Santa Monica Studio', ["Dificil", "SoulsLike", "Superacion", "Satisfactorio", "Rodar", "Mitologia"]).
juego('The Forest', ["Supervivencia", "Terror", "Accion"], 'https://store.steampowered.com/app/242760/The_Forest/', 'https://i.imgur.com/dMNz19e.jpg', 'En The Forest asumimos el papel de Eric Leblanc, padre que viaja junto a su hijo (Timmy Leblanc) en un avion. En mitad del vuelo sufrimos un terrible accidente en una peninsula remota y, aunque logramos sobrevivir al devastador impacto, presenciamos el secuestro de nuestro hijo.', 'Endnight Games Ltd', ["Crear Base", "Psicologico"]).
juego('DOOM', ["Shooter", "Accion", "Clasico"], 'https://store.steampowered.com/app/379720/DOOM/', 'https://i.imgur.com/shMaMoD.jpg', 'Los jugadores toman el papel de un marine espacial sin nombre mientras lucha contra las fuerzas demoniacas del infierno que han sido desatadas por la Union Aerospace Corporation en un planeta colonizado en el futuro, Marte.', 'Bethesda', ["Tiros", "Armas", "Sangriento", "Humor Negro", "Aliens"]).
juego('Outer Wilds', ["Exploracion", "Aventura", "Puzle"], 'https://store.steampowered.com/app/753640/Outer_Wilds/', 'https://i.imgur.com/S2ZSYa8.jpg', 'Outer Wilds es un videojuego de mundo abierto en el que podemos vivir una aventura de misterio en un sistema solar que ha quedado atrapado en un bucle temporal. El usuario debe explorar este mundo en primera persona para descubrir el secreto arcano que se esconde tras este misterio.', 'Mobius Digital', ["Buena Historia", "Psicologico", "Estetico", "Triste", "Sentimental"]).
juego('Amnesia The Dark Descent', ["Terror", "Supervivencia", "Puzle"], 'https://store.steampowered.com/app/57300/Amnesia_The_Dark_Descent/', 'https://i.imgur.com/LQSXb2N.jpg', 'El juego se desarrolla en el ano 1839, y el jugador toma el papel de Daniel, un joven de Londres que despierta en los oscuros pasillos del Castillo Brennenburg con poca memoria de si mismo y de su pasado. Todo lo que puede recordar es su nombre, que vive en Mayfair y que algo lo esta cazando.', 'Frictional Games', ["Psicologico", "Sangriento", "Buena Fisica"]).
juego('Untitled Goose Game', ["Casuales", "Indie", "Divertido"], 'https://store.steampowered.com/app/837470/Untitled_Goose_Game/', 'https://i.imgur.com/HdVLPka.jpg', 'Ubicado en un pueblo ingles de clase media, en Untitled Goose Game los jugadores controlan un ganso mientras usan su habilidad para graznar, batir sus alas y agarrar objetos con su pico para molestar a varios aldeanos humanos.', 'Panic', ["Divertido", "Chill", "Animales", "Chistes", "Tranquilidad"]).
juego('Coffee Talk', ["Conversacion", "Pixelados", "Indie"], 'https://store.steampowered.com/app/914800/Coffee_Talk/', 'https://i.imgur.com/0Re5nLI.jpg', 'es un titulo que nos pone en la piel de un barista (profesional especializado en servir cafe de gran calidad) en un Seattle actual, pero que a la vez tiene un punto de futurista, fantastico y cyberpunk, porque cuenta con enanos, elfos y orcos trabajando en distintos empleos relacionados con las tecnologias.', 'Toge Productions', ["Buena Historia", "Sentimental", "Estetico", "Chill", "Tranquilidad", "Bonito"]).
juego('Plague Inc Evolved', ["Estrategia", "Simulacion", "Indie"], 'https://store.steampowered.com/app/246620/Plague_Inc_Evolved/', 'https://i.imgur.com/H62iZ6j.jpg', 'Es una mezcla unica de estrategia y simulacion terrorificamente realista. Tu patogeno acaba de infectar al paciente cero. Ahora tu mision es extinguir a la humanidad propagando una epidemia letal mientras saboteas los esfuerzos de la poblacion para combatirla.', 'Ndemic Creations', ["Tactico", "Evolucion", "Apocalipsis"]).
juego('Elden Ring', ["Accion", "Rpg", "Fantasia Oscura"], 'https://store.steampowered.com/app/1245620/ELDEN_RING/', 'https://i.imgur.com/Coo3QtN.jpg', 'Elden Ring tiene lugar en las Tierras Intermedias, un continente ficticio gobernado por diferentes semidioses. Anteriormente estaba gobernado por la Reina Marika la Eterna, la cual actuaba como guardiana del Circulo de Elden, una poderosa fuerza que se manifiesta como el concepto fisico del orden', 'FromSoftware', ["Dificil", "SoulsLike", "Superacion", "Satisfactorio", "Rodar", "Buena Historia"]).
juego('Thymesia', ["Accion", "Rpg", "Fantasia Oscura"], 'https://store.steampowered.com/app/1343240/Thymesia/', 'https://i.imgur.com/OEBjK6T.jpg', 'Thymesia es un arduo Rpg de accion con un combate rapido y un complejo sistema de plagas como armas. En un reino donde la muerte campa a sus anchas, jugaras con el misterioso personaje Corvus. Da caza a tus enemigos, blande el poder de la enfermedad y encuentra la verdad en tus propios recuerdos.', 'Team17', ["Dificil", "SoulsLike", "Superacion", "Satisfactorio", "Rodar", "Peste Negra"]).
juego('The Mageseeker', ["Rpg", "Pixelados", "Accion"], 'https://store.steampowered.com/app/1457080/The_Mageseeker_A_League_of_Legends_Story/', 'https://i.imgur.com/1o5JwUZ.jpg', 'Juega como Sylas, un mago robahechizos que acaba de liberarse de un aprisionamiento injusto a manos de los cazadores de magos. Tendras que empunar las cadenas que en algun momento te retuvieron para liberar tus tierras de la tirania, eliminando a los cazadores de magos uno por uno.', 'Riot', ["Dificil", "Hechizos", "Magia", "Rodar", "Items"]).
juego('South Park The Fractured But Whole', ["Rpg", "Divertido", "Accion"], 'https://store.steampowered.com/app/488790/South_Park_The_Fractured_But_Whole/', 'https://i.imgur.com/3Qyr0v7.jpg', 'La narrativa del juego ocurre un dia despues de los eventos de su predecesor; sigue al Nino Nuevo, quien se ha mudado recientemente a South Park y se involucra en un epico juego de rol que implica a dos facciones rivales de superheroes compitiendo por crear sus propias franquicias mediaticas de superheroes.', 'Ubisoft', ["Humor Negro", "Divertido", "Satiras", "SuperHeroes"]).
juego('Baldurs Gate 3', ["Rpg", "Elecciones", "Sigilo"], 'https://store.steampowered.com/app/1086940/Baldurs_Gate_3/', 'https://i.imgur.com/vQpksGF.jpg', 'Reune a tu grupo y vuelve a los Reinos Olvidados en un relato de companerismo y traicion, sacrificio y supervivencia, ademas de la atraccion de un poder absoluto.', 'Larian Studios', ["Juego de Mesa", "calabozos y dragones", "Buena Historia"]).
juego('Starfield', ["Rpg", "Mundo Abierto", "Ciencia Ficcion"], 'https://store.steampowered.com/app/1716740/Starfield/', 'https://i.imgur.com/9AMCQBG.jpg', 'Starfield es el primer universo nuevo en 25 anos de Bethesda Game Studios, los galardonados creadores de The Elder Scrolls V: Skyrim y Fallout 4.', 'Bethesda', ["Buena Historia", "Realista", "Aliens"]).
juego('Cyberpunk 2077', ["Rpg", "Mundo Abierto", "CiberPunk"], 'https://store.steampowered.com/app/1091500/Cyberpunk_2077/', 'https://i.imgur.com/FTqLLre.jpg', 'Cyberpunk 2077 es un Rpg de aventura y accion de mundo abierto ambientado en el futuro sombrio de Night City, una peligrosa megalopolis obsesionada con el poder, el glamur y las incesantes modificaciones corporales.', 'CD PROJEKT', ["Buena Historia", "Desnudos", "Tiros", "Armas"]).
juego('Remnant II', ["Accion", "Aventura", "Rpg"], 'https://store.steampowered.com/app/1282100/Remnant_II/', 'https://i.imgur.com/rTEoylF.jpg', 'Remnant II es la secuela del juego superventas Remnant: From the Ashes que enfrenta a los supervivientes de la humanidad contra nuevas criaturas mortiferas y jefes divinos en mundos aterradores.', 'Gearbox Publishing', ["SoulsLike", "Tiros", "Rodar", "Armas", "Sangriento"]).
juego('Fae Farm', ["Simulacion", "Gestion", "Casuales"], 'https://store.steampowered.com/app/2230110/Fae_Farm/', 'https://i.imgur.com/T8XAb4P.jpg', 'Escapa al cuento de hadas con el que siempre ha sonado en Fae Farm. un juego de rol y simulacion para hasta 4 personas. Crea, cultiva y decora tu finca, y usa hechizos para explorar la encantadora isla Azoria. Forjaras nuevos lazos con los islenos y descubrira la magia de las hadas.', 'Phoenix Labs', ["Animales", "Vegetales", "Granja", "Chill", "Tranquilidad", "Bonito", "Magia"]).
juego('Divinity Original Sin 2', ["Estrategia", "Por Turnos", "Rpg"], 'https://store.steampowered.com/app/435150/Divinity_Original_Sin_2__Definitive_Edition/', 'https://i.imgur.com/fsvK8vJ.jpg', 'The critically acclaimed Rpg that raised the bar, from the creators of Baldur\'s Gate 3. Gather your party. Master deep, tactical combat. Venture as a party of up to four - but know that only one of you will have the chance to become a God.', 'Larian Studios', ["Tactico", "Magia", "Buena Historia"]).
juego('Sea of Stars', ["Rpg", "Por Turnos", "Pixelados"], 'https://store.steampowered.com/app/1244090/Sea_of_Stars/', 'https://i.imgur.com/G3qHAxr.jpg', 'Sea of Stars is a turn-based Rpg inspired by the classics. It tells the story of two Children of the Solstice who will combine the powers of the sun and moon to perform Eclipse Magic, the only force capable of fending off the monstrous creations of the evil alchemist known as The Fleshmancer.', 'Sabotage Studio', ["Mitologia", "Retro", "Sentimental", "Divertido", "Buena Historia", "Hechizos", "Bonito"]).
juego('Hogwarts Legacy', ["Fantasia", "Mundo Abierto", "Magia"], 'https://store.steampowered.com/app/990080/Hogwarts_Legacy/', 'https://i.imgur.com/7ag6ZwP.jpg', 'Hogwarts Legacy es un Rpg inmersivo de accion en mundo abierto. Ahora puedes tomar el control de la accion y ser el centro de tu propia aventura en el mundo magico.', 'Warner Bros', ["Magia", "Hechizos", "Buena Historia", "Amigable"]).
juego('Fallout 76', ["Rpg", "Mundo Abierto", "Multijugador"], 'https://store.steampowered.com/app/1151340/Fallout_76/', 'https://i.imgur.com/3ZVrDDU.jpg', 'Bethesda Game Studios te da la bienvenida a Fallout 76. Veinticinco anos despues de la caida de las bombas, saldras junto a los demas companeros moradores del refugio a la America posnuclear. Explora un amplio Yermo en este juego multijugador de mundo abierto que completa la historia de Fallout.', 'Bethesda', ["Buena Historia", "Tiros", "Armas", "Humor Negro", "Apocalipsis", "Online"]).
juego('SCUM', ["Supervivencia", "Zombis", "Multijugador"], 'https://store.steampowered.com/app/513710/SCUM/', 'https://i.imgur.com/C0tO4Dc.jpg', 'SCUM aims to evolve the multiplayer open world survival game with unprecedented levels of character customization, control and progression, where knowledge and skills are the ultimate weapons for long-term survival.', 'Jagex Ltd', ["Online", "Desnudos", "Sangriento", "Armas"]).
juego('Mortal Kombat 1', ["Lucha", "Accion", "Clasico"], 'https://store.steampowered.com/app/1971870/Mortal_Kombat_1/', 'https://i.imgur.com/5ZSSLEX.jpg', 'Descubre un nuevo universo de Mortal Kombat creado por Liu Kang, Dios del Fuego. Mortal Kombat 1 abre paso a una nueva era de esta iconica saga con un nuevo sistema de kombate, modos de juego y fatalities!', 'Warner Bros', ["Artes Marciales", "Sangriento", "Con Amigos", "Arcade"]).
juego('ONE PIECE PIRATE WARRIORS 4', ["Lucha", "Accion", "Anime"], 'https://store.steampowered.com/app/1089090/ONE_PIECE_PIRATE_WARRIORS_4/', 'https://i.imgur.com/1lDmfXT.jpg', 'ONE PIECE: PIRATE WARRIORS 4 pone al dia la accion de PIRATE WARRIORS! Inspirado en el concepto de experimentar un campo de batalla real de ONE PIECE, los edificios se derrumbaran durante los combates y los ataques generaran humo y polvo, para que disfrutes como nunca del mundo de ONE PIECE.', 'BANDAI NAMCO', ["Con Amigos", "Otaku", "Muchos Enemigos"]).
juego('STAR WARS Jedi Fallen Order', ["Accion", "Rpg", "Ciencia Ficcion"], 'https://store.steampowered.com/app/1172380/STAR_WARS_Jedi_La_Orden_cada/', 'https://i.imgur.com/EFfNWTU.jpg', 'Una aventura de dimensiones galacticas te espera en Star Wars Jedi: Fallen Order, un juego de aventuras y accion en tercera persona de Respawn Entertainment. Este titulo para un jugador centrado en la historia te pone en la piel de un padawan Jedi que ha escapado a duras penas de la purga de la Orden 66 despues del Episodio III: La venganza de los Sith. Para reconstruir la Orden Jedi, deberas reunir los fragmentos de tu pasado para completar tu entrenamiento, desarrollar nuevas y poderosas habilidades con la Fuerza y dominar la espada laser antes de que el Imperio y sus mortiferos inquisidores te alcancen.', 'Electronic Arts', ["SoulsLike", "Parkour", "Buena Musica", "Rodar", "Aliens", "Pelicula"]).
juego('TEKKEN 8', ["Lucha", "Accion", "Clasico"], 'https://store.steampowered.com/app/1778820/TEKKEN_8/', 'https://i.imgur.com/0ZERWVK.png', 'Preparate para el proximo capitulo de la legendaria franquicia del juego de lucha: TEKKEN 8.', 'Bandai Namco', ["Artes Marciales", "Sangriento", "Con Amigos", "Arcade"]).
juego('ONE PUNCH MAN A HERO NOBODY KNOWS', ["Accion", "Lucha", "Anime"], 'https://store.steampowered.com/app/991560/ONE_PUNCH_MAN_A_HERO_NOBODY_KNOWS/', 'https://i.imgur.com/kBStvFj.jpg', 'Sumergente en un juego de lucha dinamico con los famosos personajes de One Punch Man! Haz de tu heroe preferido o conviertete tu en uno!', 'BANDAI NAMCO', ["Online", "Divertido"]).
juego('Mortal Kombat X', ["Lucha", "Accion", "Clasico"], 'https://store.steampowered.com/app/307780/Mortal_Kombat_X/', 'https://i.imgur.com/m9I1U8r.jpg', 'Disfruta de la nueva generacion de la franquicia de lucha n. 1. Mortal Kombat X reune un aspecto cinematografico y una mecanica de juego nunca vistos.', 'Warner Bros', ["Artes Marciales", "Sangriento", "Con Amigos", "Arcade"]).
juego('DAVE THE DIVER', ["Gestion", "Casuales", "Pixelados"], 'https://store.steampowered.com/app/1868140/DAVE_THE_DIVER/', '4', 'DAVE THE DIVER es un juego casual de rol y aventuras para un solo jugador que incluye elementos de pesca y exploracion del fondo marino durante el dia y de gestion de un restaurante de sushi durante la noche. Ayuda a Dave y a sus extranos amigos a destapar los secretos de la misteriosa Fosa Azul.', 'MINTROCKET', ["Bonito", "Chill", "Tranquilidad", "SubAcuatico", "Animales", "Farmear"]).
juego('Football Manager 2023', ["Simulacion", "Deportes", "Gestion"], 'https://store.steampowered.com/app/1904540/Football_Manager_2023/', 'https://i.imgur.com/CsIMoRX.jpg', 'Confecciona la plantilla de tus suenos, supera a tus rivales y vive la emocion de las grandes noches europeas en la UEFA Champions League. Emprende tu viaje hacia la gloria.', 'SEGA', ["Futbol", "Tactico", "Chill"]).
juego('Farming Simulator 22', ["Simulacion", "Gestion", "Casuales"], 'https://store.steampowered.com/app/1248130/Farming_Simulator_22/', 'https://i.imgur.com/L0DqLdW.jpg', 'Crea tu propia granja y cosecha diversion! Siembra cultivos, cuida de los animales, gestiona la produccion y enfrentate al desafio de las estaciones.', 'Giants Software', ["Vegetales", "Granja", "Chill"]).
juego('Digimon World Next Order', ["Coleccion de Criaturas", "Rpg", "Anime"], 'https://store.steampowered.com/app/1530160/Digimon_World_Next_Order/', 'https://i.imgur.com/PihyH3C.jpg', 'El Mundo Digital ha sido asaltado por Machinedramon y ahora esta en el caos mas absoluto. Como un Digidestinado, debes restaurar el orden en el mundo en Digimon World: Next Order, un Rpg de coleccionar monstruos.', 'Bandai Namco', ["Bonito", "Chill", "Farmear"]).
juego('Monster Hunter Stories 2 Wings of Ruin', ["Coleccion de Criaturas", "Rpg", "Aventura"], 'https://store.steampowered.com/app/1277400/Monster_Hunter_Stories_2_Wings_of_Ruin/', 'https://i.imgur.com/xYbpKZ5.jpg', 'Nueva aventura en la segunda entrega de esta serie de juegos de rol por turnos ambientada en el mundo de Monster Hunter! Conviertete en un Rider y unete a monstruos amistosos (los llamados Monsties) parar luchar a su lado embarcandote en una historia epica.', 'CAPCOM', ["Con Amigos", "Online", "Buena Musica", "Farmear", "SoulsLike"]).
juego('Flutter Away', ["Casuales", "Coleccion de Criaturas", "Exploracion"], 'https://store.steampowered.com/app/2224030/Flutter_Away/', 'https://i.imgur.com/aID4b6n.jpg', 'Disfruta de la serenidad de la selva amazonica en este breve juego de exploracion de la naturaleza tan agradable. Como investigador de mariposas en un viaje de cinco dias, explora los senderos cercanos, saca fotografias, conoce animales amistosos y de paso documenta tus descubrimientos!', 'Runaway Play', ["Animales", "Carpincho", "Bonito", "Estetico", "Chill"]).
juego('Stray', ["Aventura", "CiberPunk", "Indies"], 'https://store.steampowered.com/app/1332010/Stray/', 'https://i.imgur.com/t29EVsY.jpg', 'Perdido, solo y separado de su familia, un gato callejero debe desentranar un antiguo misterio para escapar de una ciberciudad olvidada y encontrar el camino a casa.', 'Annapurna Interactive', ["Buena Historia", "Animales", "Bonito", "Sentimental", "Triste"]).
juego('The Walking Dead', ["Zombis", "Aventura", "Elecciones"], 'https://store.steampowered.com/app/207610/The_Walking_Dead/', 'https://i.imgur.com/HVbXMkX.jpg', 'Una aventura de terror en cinco entregas ambientada en el mismo universo que la galardonada serie de comics de Robert Kirkman.', 'Telltale Games', ["Buena Historia", "Apocalipsis", "Triste", "Sentimental"]).
juego('Before Your Eyes', ["Elecciones", "Indies", "Casuales"], 'https://store.steampowered.com/app/1082430/Before_Your_Eyes/', 'https://i.imgur.com/JCCHtf5.jpg', 'Embarcate en una conmovedora aventura narrativa en primera persona, en la que dirigiras la historia y alteraras su curso con parpadeos. Esta innovadora tecnica te permitira sumergirte de lleno en un mundo repleto de recuerdos, entranables y dolorosos, mientras ves la vida pasar ante tus ojos.', 'Skybound Games', ["Buena Historia", "Sentimental", "Psicologico", "Misterio"]).
juego('Tomb Raider', ["Aventura", "Accion", "Puzle"], 'https://store.steampowered.com/app/203160/Tomb_Raider/', 'https://i.imgur.com/yQNnTPH.jpg', 'Tomb Raider relata la historia del origen de Lara Croft y su transformacion de una joven chica a una endurecida superviviente.', 'Crystal Dynamics', ["Buena Historia", "Tiros"]).
juego('Ori and the Will of the Wisps', ["Metroidvaina", "Plataformas", "Exploracion"], 'https://store.steampowered.com/app/1057090/Ori_and_the_Will_of_the_Wisps/', 'https://i.imgur.com/6KDw8pE.jpg', 'Comienza un nuevo viaje por un mundo enorme y exotico en el que encontraras imponentes enemigos y Puzle desafiantes en tu mision para desentranar el destino de Ori.', 'Xbox Game', ["Bonito", "Estetico", "Sentimental", "SoulsLike", "Dificil"]).
juego('GRIS', ["Plataformas", "Exploracion", "Indies"], 'https://store.steampowered.com/app/683320/GRIS/', 'https://i.imgur.com/QfsGSy7.jpg', 'Gris es una muchacha llena de esperanzas y perdida en su propio mundo, enfrentada a una experiencia dolorosa de su vida.', 'Devolver Digital', ["Buena Musica", "Bonito", "Estetico", "Sentimental", "Tranquilidad"]).
juego('My Friend Pedro', ["Accion", "Shooter", "Indies"], 'https://store.steampowered.com/app/557340/My_Friend_Pedro/', 'https://i.imgur.com/k69rMgd.jpg', 'My Friend Pedro es un ballet violento sobre la amistad, la imaginacion y la lucha de un hombre por aniquilar a todo el que se interpone en su camino por orden de un platano parlante.', 'Devolver Digital', ["Tiros", "Armas", "Sangriento", "Divertido"]).
juego('DOOM 1993', ["Accion", "Shooter", "Clasico"], 'https://store.steampowered.com/app/2280/DOOM_1993/', 'https://i.imgur.com/hgffj4C.jpg', 'Eres uno de los mejores marines de la Tierra, destinado en la instalacion de investigacion de la UAC en Marte. Un fallo en un experimento abre un portal al infierno y unos demonios sanguinarios infestan la base. Deberas abrirte paso a tiros para poder sobrevivir.', 'id Software', ["Retro", "Armas", "Tiros", "Sangriento"]).
juego('Quake', ["Accion", "Shooter", "Clasico"], 'https://store.steampowered.com/app/2310/Quake/', 'https://i.imgur.com/lVLDzV6.jpg', 'Desarrollado por el galardonado equipo de id Software, Quake es el innovador shooter en primera persona de fantassa oscura que inspiro los shooters de estilo retro de hoy en dia. Con Quake (Enhanced), disfruta de la version autentica, actualizada y visualmente mejorada del original.', 'id Software', ["Retro", "Armas", "Tiros", "Sangriento", "Aliens"]).
juego('Orcs Must Die!', ["Construccion De Bases", "Estrategia", "Accion"], 'https://store.steampowered.com/app/102600/Orcs_Must_Die/', 'https://i.imgur.com/ORW8eja.jpg', 'Rebanalos, incinrralos, empalalos, arrojalos - da igual como lo hagas. Los orcos deben morir en este juego de acciin y estrategia de la mano de Robot Entertainment.En la piel de un poderoso mago de guerra con un arsenal de mortiferas armas, hechizos y trampas al alcance de tu mano, te toca defender veinticuatro fortalezas del azote de los enemigos', 'Robot Entertainment', ["Tactico", "Con Amigos", "Divertido"]).
juego('POSTAL Brain Damaged', ["Shooter", "Accion", "Divertido"], 'https://store.steampowered.com/app/1359980/POSTAL_Brain_Damaged/', 'https://i.imgur.com/moNsz5f.jpg', 'POSTAL: Brain Damaged is a new, action-oriented take on the Running With Scissors cult game series with throwback graphics, and fast-paced, modern gameplay. Take a wild roller coaster ride through the twisted wonderland encased in the POSTAL DUDES messed-up mind.', 'Hyperstrange', ["Retro", "Armas", "Tiros", "Sangriento", "Humor Negro", "Arcade"]).
juego('Capybara Spa', ["Simulacion", "Casuales", "Sandbox"], 'https://store.steampowered.com/app/1822910/Capybara_Spa/', 'https://i.imgur.com/PlHqNxf.jpg', 'Construye tu propio spa de capibaras en este simulador relajante repleto de ternura! Cosecha frutos, fabrica jabones y limpia toallas para consentir a los capibaras durante su visita. Decora la montana con jardines, tinas y adornos para tener el mejor spa de todos!', 'Cozy Bee Games', ["Animales", "Carpincho", "Bonito", "Estetico", "Chill"]).
juego('DisneyPixar WALLE', ["Aventura", "Ciencia Ficcion", "Casuales"], 'https://store.steampowered.com/app/331750/DisneyPixar_WALLE/', 'https://i.imgur.com/LDSxwsa.jpg', 'Based on the 2008 computer animated film from Pixar Animation Studios, the video game version of WALL-E involves playing as the lonely robot as he navigates a trash-tainted world and begins an unlikely trek across the cosmos.', 'Disney', ["Chill", "Bonito", "Pelicula"]).
juego('Age of Empires II', ["Estrategia", "ETR", "Multijugador"], 'https://store.steampowered.com/app/221380/Age_of_Empires_II_2013/', 'https://i.imgur.com/TkMBOZ6.jpg', 'Age of Empires II ha entrado al mundo de la alta definicion sumando ademas nuevas funciones y ajustes, mejoras en la inteligencia artificial, cromos de Steam, soporte para Steam Workshop, integracion con Steamworks, y mas!', 'Xbox Game', ["Tactico", "Retro", "Con Amigos", "Online", "Civilizacion"]).
juego('Devil May Cry 5', ["Accion", "Divertido", "Clasico"], 'https://store.steampowered.com/app/601150/Devil_May_Cry_5/', 'https://i.imgur.com/R5NqHYL.jpg', 'El cazademonios definitivo vuelve con estilo en el juego que los fans de la accion estaban esperando.', 'CAPCOM', ["Muchos Enemigos", "Divertido", "Chistes", "Desnudos", "Sangriento"]).
juego('Killing Floor', ["Zombis", "Shooter", "Multijugador"], 'https://store.steampowered.com/app/1250/Killing_Floor/', 'https://i.imgur.com/DZehZA7.jpg', '6-player co-op survival horror at its finest! Free updates, free special events and a ridiculous amount of fun!', 'Tripwire Interactive', ["Tiros", "Armas", "Con Amigos", "Sangriento"]).
juego('Spiritfarer', ["Elecciones", "Indie", "Gestion"], 'https://store.steampowered.com/app/972660/Spiritfarer_Edicin_Farewell/', 'https://i.imgur.com/5qpUgI5.jpg', 'Spiritfarer es un juego de gestion sobre la muerte. Como maestre de un ferri que transporta a las almas, deberas construir un barco para explorar el mundo, cuidar de tus amigos espiritus y guiarlos camino del mas alla. Incluye el juego base y tres actualizaciones de contenido importantes.', 'Thunder Lotus Games', ["Sentimental", "Triste", "Tranquilidad", "Buena Historia", "Bonito"]).
juego('Crypt of the NecroDancer', ["Rogue Like", "Pixelados", "Indies"], 'https://store.steampowered.com/app/247080/Crypt_of_the_NecroDancer/', 'https://i.imgur.com/lGKj4cZ.jpg', 'Crypt of the NecroDancer es un galardonado juego hardcore estilo roguelike ritmico. Muevete con la musica y da palizas con el ritmo! Baila con la epica musica de Danny Baranowsky, o elige canciones de tu propia coleccion MP3!', 'Brace Yourself Games', ["Runs", "Items", "Buena Musica"]).
juego('Yakuza Like a Dragon', ["Rpg", "Por Turnos", "Divertido"], 'https://store.steampowered.com/app/1235140/Yakuza_Like_a_Dragon/', 'https://i.imgur.com/5lEkpyj.jpg', 'Conviertete en Ichiban Kasuga, un yakuza de bajo rango al que el hombre en el que mas confiaba dejo al borde de la muerte. Agarra tu bate legendario y preparate para reventar craneos de los bajos fondos en un dinamico combate Rpg ambientado en el Japon actual.', 'SEGA', ["Divertido", "Chistes", "Desnudos"]).
juego('Reventure', ["Divertido", "Pixelados", "Indies"], 'https://store.steampowered.com/app/900270/Reventure/', 'https://i.imgur.com/yNT18I4.jpg', 'Por que tiene tan buenas reviews un juego con esos graficos tan pixelados? Sera por lo de los 100 finales? Voy a pillarlo solo por curiosidad y si no me gusta pido un refund', 'Pixelatto', ["Divertido", "Chistes", "Humor Negro", "Revolucionario"]).
juego('DOOM II', ["Accion", "Shooter", "Clasico"], 'https://store.steampowered.com/app/2300/DOOM_II/', 'https://i.imgur.com/08PcgIB.jpg', 'El infierno ha invadido la Tierra y, para salvarla, deberas luchar contra demonios mas poderosos aun usando armas mas potentes todavia. En la secuela del revolucionario DOOM (1993) aparecen la superescopeta, el infame Icono del Pecado y mas accion a raudales de FPS.', 'id Software', ["Retro", "Armas", "Tiros", "Sangriento"]).
juego('Poly Bridge 2', ["Construccion", "Simulacion", "Puzle"], 'https://store.steampowered.com/app/1062160/Poly_Bridge_2/', 'https://i.imgur.com/tj3UovH.jpg', 'El aclamado simulador de construccion de puentes ha vuelto y mejor que nunca! Vuelve a descubrir tu creatividad ingenieril con mas horas de desafiante diversion!', 'Dry Cactus', ["Chill", "Estetico", "Buena Fisica"]).
juego('Vampire Survivors', ["Rogue Like", "Bullet Hell", "Accion"], 'https://store.steampowered.com/app/1794680/Vampire_Survivors/', 'https://i.imgur.com/xVXZMXz.jpg', 'Aniquila a miles de criaturas de la noche y sobrevive hasta el amanecer! Vampire Survivors es un juego casual de terror gotico con elementos roguelite donde tus decisiones te permitiran aumentar tu poder exponencialmente mientras luchas contra cientos de monstruos.', 'poncle', ["Retro", "Runs", "Items", "Chill"]).
juego('A Short Hike', ["Aventura", "Exploracion", "Casuales"], 'https://store.steampowered.com/app/1055540/A_Short_Hike/', 'https://i.imgur.com/7LCTo0I.jpg', 'Trepa, camina, y vuela a traves de los tranquilos paisajes de la montana del Parque Provincial Picohalcon en tu camino a la cima.', 'adamgryu', ["Chill", "Tranquilidad", "Bonito"]).
juego('Not For Broadcast', ["Aventura", "Simulacion", "Elecciones"], 'https://store.steampowered.com/app/1147550/Not_For_Broadcast/', 'https://i.imgur.com/fBhA5XI.jpg', 'El Informativo Nacional Nocturno esta en antena y eres el cerebro de la operacion. Censura tacos, enfoca bien a los famosos y engancha a la audiencia en este juego de humor negro y caos televisivo.', 'tinyBuild', ["Chill", "Buena Trama", "Humor Negro"]).
juego('Clash Artifacts of Chaos', ["Accion", "Aventura", "Rpg"], 'https://store.steampowered.com/app/1430680/Clash_Artifacts_of_Chaos/', 'https://i.imgur.com/kJOUZ6Q.jpg', 'Perseguido por los mercenarios de un enemigo de poder inimaginable, el guerrero Pseudo y la criatura bajo su proteccion emprenden una peligrosa mision en los confines de tierras desconocidas.', 'Nacon', ["SoulsLike", "Buena Historia", "Revolucionario", "Rodar"]).
juego('Deaths Door', ["Accion", "Aventura", "Rpg"], 'https://store.steampowered.com/app/894020/Deaths_Door/', 'https://i.imgur.com/0TWfEdl.jpg', 'Cosechar las almas de los muertos y fichar en tu puesto puede hacerse monotono, pero es un trabajo honrado para un cuervo. La cosa se anima cuando roban el alma que tienes asignada y tienes que seguirle el rastro a un ladron desesperado hasta un mundo que la muerte no ha tocado.', 'Devolver Digital', ["SoulsLike", "Rodar"]).
juego('DRAGON BALL Z KAKAROT', ["Accion", "Rpg", "Anime"], 'https://store.steampowered.com/app/851850/DRAGON_BALL_Z_KAKAROT/', 'https://i.imgur.com/y8nALjR.jpg', 'Revive la historia de Son Goku y otros Guerreros Z en DRAGON BALL Z: KAKAROT! Conoce el mundo de DRAGON BALL Z no solo por sus epicos combates, sino tambien mientras luchas, pescas, comes y entrenas con Son Goku, Son Gohan, Vegeta y muchos mas.', 'Bandai Namco', ["Dificil", "Buena Historia"]).
juego('Haven', ["Rpg", "Accion", "CiberPunk"], 'https://store.steampowered.com/app/983970/Haven/', 'https://i.imgur.com/kX44i0z.jpg', 'Dos amantes lo dejan todo y escapan a un remoto planeta para estar juntos. Deslizate por misteriosos paisajes, explora un mundo hecho pedazos y enfrentate a quienes buscan separarlos en este Rpg de aventuras sobre el amor, la rebelion y la libertad.', 'The Game Bakers', ["Buena Historia", "Divertdo", "Con Amigos"]).
juego('Kena Bridge of Spirits', ["Accion", "Aventura", "Rpg"], 'https://store.steampowered.com/app/1954200/Kena_Bridge_of_Spirits/', 'https://i.imgur.com/VZLFVc6.jpg', 'Una aventura de accion basada en una historia que combina la exploracion con el combate vertiginoso. Desenreda el pasado en la piel de Kena, una joven guia espiritual en busqueda del sagrado Santuario de la montana.', 'Ember Lab', ["Dificil", "SoulsLike", "Superacion", "Satisfactorio", "Rodar", "Magia"]).
juego('Starbound', ["Sandbox", "Aventura", "Pixelados"], 'https://store.steampowered.com/app/211820/Starbound/', 'https://i.imgur.com/zo8C5Z8.jpg', 'You have fled your home, only to find yourself lost in space with a damaged ship. Your only option is to beam down to the planet below, repair your ship and set off to explore the universe...', 'Chucklefish', ["Bloques", "Farmear", "Crear Mundo", "Crear Base"]).
juego('Chained Echoes', ["Rpg", "Por Turnos", "Indie"], 'https://store.steampowered.com/app/1229240/Chained_Echoes/', 'https://i.imgur.com/R9nb7CG.jpg', 'Coge tu espada, canaliza tu magia o subete a tu Mech. Chained Echoes es un Rpg con una estetica clasica de 16 bits. La historia se desarrolla en un mundo de fantasia donde es tan facil encontrarse con dragones como con trajes mecanicos dirigibles.', 'Deck13', ["Mitologia", "Retro", "Sentimental", "Divertido", "Buena Historia", "Hechizos", "Bonito"]).
juego('Dicey Dungeons', ["Rogue Like", "Cartas", "Indies"], 'https://store.steampowered.com/app/861540/Dicey_Dungeons/', 'https://i.imgur.com/fbn8U9r.jpg', 'Un dinamico juego roguelike de construccion de mazo creado por Terry Cavanagh (Super Hexagon, VVVVVV), Chipzel y Marlowe Dobbe. Lucha contra monstruos, encuentra el mejor botin, sube de nivel a tus heroes e intenta doblegar a la mismisima diosa Fortuna. Equilibra tus estrategias planeadas cuidadosamente ante la incertidumbre de una tirada de dados.', 'Terry Cavanagh', ["Cartas", "Chill"]).
juego('Curse of the Dead Gods', ["Rogue Like", "Accion", "Fantasia Oscura"], 'https://store.steampowered.com/app/1123770/Curse_of_the_Dead_Gods/', 'https://i.imgur.com/OwIeWSE.jpg', 'Buscas riquezas incontables, la vida eterna, poder divino y todo te lleva a este templo maldito, un laberinto aparentemente infinito con fosos sin fondo, trampas mortales y monstruos.', 'Focus Entertainment', ["Dificil", "SoulsLike", "Sangriento", "Runs", "Rodar"]).
juego('Strayed Lights', ["Accion", "Aventura", "Puzle"], 'https://store.steampowered.com/app/2162020/Strayed_Lights/', 'https://i.imgur.com/Jsb4OqN.jpg', 'Una aventura de accion con una gran atmosfera, que combina una experiencia sin palabras con luchas cinematograficas basadas en colores. Restaura tu luz, destruida por las sombras y enfrenta a entranables criaturas deformadas por sus emociones.', 'Embers', ["Buena Historia", "Revolucionario", "Estetico", "Bonito"]).
juego('Darksiders III', ["Accion", "Aventura", "Rpg"], 'https://store.steampowered.com/app/606280/Darksiders_III/', 'https://i.imgur.com/gkr5ggM.jpg', 'Regresa a una Tierra apocaliptica en Darksiders III, una aventura de accion hack-n-slash en la que los jugadores adoptan el papel de Fury, cuya mision es perseguir y deshacerse de los siete Pecados Capitales.', 'THQ Nordic', ["Dificil", "SoulsLike", "Superacion", "Satisfactorio", "Rodar"]).
juego('The Knight Witch', ["Metroidvaina", "Bullet Hell", "Plataformas"], 'https://store.steampowered.com/app/1872680/The_Knight_Witch/', 'https://i.imgur.com/nc1PiB1.jpg', 'The Knight Witch es una aventura shoot\'em up con toques de metroidvania, ambientada en un hermoso mundo dibujado a mano. Lanza hechizos devastadores con las cartas, forja vinculos y toma decisiones en tu mision por salvar tu hogar y descubrir quien se esconde tras la invasion de los golems.', 'Team17', ["Retro", "Runs", "Items", "Magia", "Hechizos"]).
juego('Forspoken', ["Accion", "Mundo Abierto", "Rpg"], 'https://store.steampowered.com/app/1680880/Forspoken/', 'https://i.imgur.com/LwwIVra.jpg', 'Forspoken narra la historia de Frey, una joven neoyorquina que acaba en el hermoso y cruel mundo de Athia. Mientras averigua como volver a casa, tendra que usar sus nuevas dotes magicas para recorrer paisajes enormes y enfrentarse a seres monstruosos.', 'Square Enix', ["Dificil", "SoulsLike", "Psicologico"]).
juego('Wu Long Fallen Dynasty', ["Accion", "Aventura", "Rpg"], 'https://store.steampowered.com/app/1448440/Wu_Long_Fallen_Dynasty/', 'https://i.imgur.com/3xT0NtJ.jpg', 'Wu Long: Fallen Dynasty es un juego de rol de accion con elementos de hack\'n\'slash ambientado en un mundo de fantasia inspirado en la mitologia china. Lucha contra hordas de enemigos y enfrentate a desafiantes jefes en tu viaje para restaurar el equilibrio entre el cielo y la tierra.', 'KOEI TECMO GAMES CO', ["Dificil", "SoulsLike", "Superacion", "Satisfactorio", "Rodar"]).
juego('Wizard with a Gun', ["Rogue Like", "Accion", "Aventura"], 'https://store.steampowered.com/app/1150530/Wizard_with_a_Gun/', 'https://i.imgur.com/VEw1ThL.jpg', 'Wizard with a Gun es un juego de supervivencia cooperativo en linea estilo sandbox, ambientado en una naturaleza magica y salvaje repleta de criaturas peligrosas y misterios arcanos.', 'Devolver Digital', ["Dificil", "Superacion", "Buena Historia", "Rodar", "Runs", "Items", "Divertido"]).


recuperar_categorias(Juego, Categorias) :-
    juego(Juego, Categorias, _, _, _, _, _).

%con findall busca todos los juegos que cumplen que Lista sea sublista de Categoria con el forall y el member, y esos juegos los guarda en Resultado. 
recuperar_juegos_con_categorias(Lista, Resultado) :-
    findall(Juego, (
        juego(Juego, Categorias, _, _, _, _, _),
        forall(member(Categoria, Lista), member(Categoria, Categorias))
    ), Resultado).

recuperar_imagen(Juego, Imagen) :-
    juego(Juego, _, _, Imagen, _, _, _).

recuperar_link(Juego, Link) :-
    juego(Juego, _, Link, _, _, _, _).

recuperar_sinopsis(Juego, Sinopsis) :-
    juego(Juego, _, _, _, Sinopsis, _, _).

element_exists(X, Result) :-
    categorias(Lista),
    (member(X, Lista) -> Result = "true" ; Result = "false").

exist_juego(Titulo, Result) :-
    (juego(Titulo, _, _, _, _, _, _) -> Result = "true" ; Result = "false").

recuperar_todas_las_categorias(Resultado) :-
    categorias(Resultado).

recuperar_Desarrolador(Juego, Desarrolador) :-
    juego(Juego, _, _, _, _, Desarrolador, _).

recuperar_Pal_Claves(Juego, Pal) :-
    juego(Juego, _, _, _, _, _, Pal).

% Regla para imprimir el juego en formato CSV y devolver el resultado
imprimir_juego(Nombre, Generos, Desarrollador, PalabrasClaves, Resultado) :-
    atomic_list_concat(Generos, ',', GenerosStr),
    atomic_list_concat(PalabrasClaves, ',', PalabrasClavesStr),
    format(atom(Resultado), '~w;~w;~w;~w', [Nombre, GenerosStr, Desarrollador, PalabrasClavesStr]).

imprimir_juego_unico(Nombre, Resultado) :-
    juego(Nombre, Generos, _, _, _, Desarrollador, PalabrasClaves),
    imprimir_juego(Nombre, Generos, Desarrollador, PalabrasClaves, Resultado).

% Regla para imprimir todos los juegos en formato CSV y devolver el resultado
imprimir_todos_los_juegos(Resultado) :-
    findall(Juego, (
        juego(Nombre, Generos, _, _, _, Desarrollador, PalabrasClaves),
        imprimir_juego(Nombre, Generos, Desarrollador, PalabrasClaves, Juego)
    ), Resultado).

% Regla para imprimir todos los juegos excepto los que están en la lista de nombres y devolver el resultado
imprimir_todos_los_juegos_excepto_nombres(Nombres, Resultado) :-
    findall(Juego, (
        juego(Nombre, Generos, _, _, _, Desarrollador, PalabrasClaves),
        \+ member(Nombre, Nombres),
        imprimir_juego(Nombre, Generos, Desarrollador, PalabrasClaves, Juego)
    ), Resultado).

% pasar la lista como imprimir_todos_los_juegos_excepto_nombres(['Dark Souls']). es decir con ''