categorias(["Accion", "RPG", "Aventura", "Casuales", "Indies", "Carreras", "Simulacion", "Deportes", "Rogue Like", "Plataformas", "Puzles", "Cartas", "Sandbox", "Bullet Hell", "Construccion", "Ciencia Ficcion", "Pixelados", "Exploracion", "Por Turnos", "Gestion", "Shooter", "Habilidad", "Estrategia", "Mundo Abierto", "Multijugador", "Viaje en el Tiempo", "Sigilo", "Narrativa", "Fantasia", "Fantasia Oscura", "Supervivencia", "Coleccion de Criaturas", "Survival Horror", "Estrategia en Tiempo Real", "Lucha", "ETR", "Construccion De Bases", "Terror", "Zombis", "Elecciones", "Metroidvaina", "Clicker", "Clasico", "Divertido", "Conversacion"]).
juego('Dark Souls', ["Accion", "RPG", "Aventura"], 'https://store.steampowered.com/app/570940/DARK_SOULS_REMASTERED/', 'darksouls.jpg', 'Dark Souls es el nuevo juego de rol y accion de los creadores de Demons Souls, FromSoftware. Dark Souls cuenta con muchos elementos ya conocidos: un universo fantastico y oscuro, tortuosos recorridos por mazmorras, temibles enemigos e interacciones online exclusivas. Sin embargo, Dark Souls es el sucesor espiritual de Demons Souls, no una secuela. Preparate para un nuevo mundo que induce a ladesesperacion, provisto de un amplio horizonte totalmente explorable y de relieves geograficos dispuestos en vertical. Preparate para una historia nueva y misteriosa que giraen torno al mundo de Lodran. Y, sobre todo, preparate para morir. Te enfrentaras a innumerables trampas mortales, a incontables hordas oscuras y grotescas y a varios jefesdemonios y dragones descomunales de una fuerza impresionante. Tendras que aprender de la muerte para sobrevivir en este mundo implacable').
juego('Hades', ["Accion", "Indies", "Rogue Like"], 'https://store.steampowered.com/app/400/Portal/', 'hades.jpg', 'Desafia al dios de los muertos, Hades, y protagoniza comoZagreus una salvaje fuga del Inframundo con el objetivo de descubrir secretos de tu pasado.').
juego('Portal', ["Puzles", "Ciencia Ficcion", "Accion"], 'https://store.steampowered.com/app/400/Portal/', 'portal.jpg', 'Un sujeto de prueba se despierta en una instalacion cientifica controlada por una inteligencia artificial sadica y debe escapar con la ayuda del unico instrumento que tiene: una pistola que hace portales dimensionales.').
juego('Stardew Valley', ["Sandbox", "Simulacion", "Gestion"], 'https://store.steampowered.com/app/1145360/Hades/', 'stardew.jpg', 'Stardew Valley es un juego de simulacion de granja inspirado en juegos como Harvest Moon. Al principio del juego, el jugador crea su personaje, pudiendo elegir el sexo del mismo, color y tipo de cabello, entre otros. El jugador recibela granja en ruinas que alguna vez poseyo su abuelo.').
juego('The Binding of Isaac', ["Indies", "Rogue Like", "Accion"], 'https://store.steampowered.com/app/250900/The_Binding_of_Isaac_Rebirth/', 'thebindingofisaac.jpg', 'En el transcurso del viaje de un chico llamado Isaac, que tras los incontables abusos de su madre religiosa emprende un viaje por su sotano, en el cual los jugadores encontraran extranos tesoros  que cambiaran la forma de Isaac, le daran habilidades y poderes sobrehumanos que le permitiran luchar  contra hordas de criaturas aterradoras y diabolicas, descubrir secretos y abrirse camino a su supervivencia.').
juego('Dead Cells', ["Metroidvaina", "Rogue Like", "Accion"], 'https://store.steampowered.com/app/588650/Dead_Cells/', 'deadcells.png', 'Dead Cells es un videojuego de accion y plataformas en 2D con mapas muy grandes, en los que los jugadores podran perderse y explorar a placer, encontrando secretos, nuevas armas, artefactos y habilidades con las que  mejorar a nuestro personaje.').
juego('Hotline Miami', ["Accion", "Indies", "Pixelados"], 'https://store.steampowered.com/app/219150/Hotline_Miami/', 'hotlinemiami.jpg', 'Ambientado en un Miami alternativo de 1989, asumiras el papel de un antiheroe misterioso en un alboroto asesino contra el inframundo turbio a instancias de las voces en tu contestador automatico. Pronto te encontraras luchando  por entender lo que esta pasando y por que eres propenso a estos actos de violencia.').
juego('Terraria', ["Sandbox", "Aventura", "Pixelados"], 'https://store.steampowered.com/app/105600/Terraria/', 'terraria.jpg', 'Terraria es un videojuego de mundo abierto en 2D. Contiene elementos de construccion, exploracion, aventura y combate, muy similar a juegos clasicos de la consola Super NES, como por ejemplo la serie Metroid, y a otras entregas  no tan antiguas como Minecraft. El juego comienza en un mundo creado de forma aleatoria.').
juego('Minecraft', ["Sandbox", "Construccion", "Aventura"], 'https://www.minecraft.net/es-es/store/minecraft-deluxe-collection-pc', 'minecraft.png', 'Minecraft es un videojuego tipo sandbox, su traduccion literal seria caja de arena y es lo que representa la experiencia de juego. Los jugadores pueden modelar el mundo a su gusto, destruir y construir, como si  estuviesen jugando en una caja de arena.').
juego('Brotato', ["Rogue Like", "Bullet Hell", "Accion"], 'https://store.steampowered.com/app/1942280/Brotato/', 'brotato.jpg', 'Brotato es un roguelite de disparos en el que te moveras de arriba abajo del escenario. Encarna a una patata con 6 armas simultaneas para hacer frente a los alienigenas. Elige entre una variedad de caracteristicas y objetos para  crear combinaciones unicas y sobrevivir hasta que acudan los refuerzos.').
juego('Downwell', ["Rogue Like", "Plataformas", "Indies"], 'https://store.steampowered.com/app/360740/Downwell/', 'downwell.jpg', 'Downwell es un curioso juego sobre un joven que se aventura en un pozo en busca de tesoros olvidados con la unica ayuda de sus botas-pistola para protegerse. Abrete camino entre la oscuridad habitada por temibles criaturas y  misteriosos secretos para conseguir las espectaculares gemas rojas repartidas por las rocas.').
juego('Bastion', ["RPG", "Accion", "Indies"], 'https://store.steampowered.com/app/107100/Bastion/', 'bastion.jpg', 'Bastion es un juego bidimensional que utiliza un punto de vista isometrico y cuenta con una narracion dinamica que interactua con el personaje mientras este avanza. El juego fue desarrollado en un periodo de dos anos por un equipo de siete personas divididas entre las ciudades de San Jose y Nueva York.').
juego('Enter the Gungeon', ["Rogue Like", "Bullet Hell", "Accion"], 'https://store.steampowered.com/app/311690/Enter_the_Gungeon/', 'enterthegungeon.jpg', 'Bastion es un juego bidimensional que utiliza un punto de vista isometrico y cuenta con una narracion dinamica que interactua con el personaje mientras este avanza. El juego fue desarrollado en un  periodo de dos anos por un equipo de siete personas divididas entre las ciudades de San Jose y Nueva York.').
juego('Kenshi', ["RPG", "Sandbox", "Construccion"], 'https://store.steampowered.com/app/233860/Kenshi/', 'kenshi.jpg', 'Kenshi es un juego de rol multijugador y supervivencia en un gigantesco mundo abierto. En Kenshi, los jugadores encontraran elementos tipicos del genero del rol, asi como la posibilidad de construir ciudades y fortalezas. El titulo tiene lugar en un mundo de canibales, criaturas extranas y duras condiciones climaticas.').
juego('Game Dev Tycoon', ["Simulacion", "Indies", "Gestion"], 'https://store.steampowered.com/app/239820/Game_Dev_Tycoon/', 'gamedevtycoon.jpg', 'Kenshi es un juego de rol multijugador y supervivencia en un gigantesco mundo abierto. En Kenshi, los jugadores encontraran elementos tipicos del genero del rol, asi como la posibilidad de construir ciudades y fortalezas.  El titulo tiene lugar en un mundo de canibales, criaturas extranas y duras condiciones climaticas.').
juego('Sekiro', ["Accion", "RPG", "Aventura"], 'https://store.steampowered.com/app/814380/Sekiro_Shadows_Die_Twice__GOTY_Edition/', 'sekiro.jpg', 'Sekiro: Shadows Die Twice es un videojuego de accion-aventura desarrollado por FromSoftware y publicado por Activision. Dirigido por Hidetaka Miyazaki; se estreno el 22 de marzo de 2019 para PlayStation 4, Xbox One y Microsoft  Windows. Su historia la protagoniza un shinobi llamado Sekiro durante el periodo Sengoku, cuya intencion es la de vengarse de un samurai que le ataco y secuestro a su senor.').
juego('Transistor', ["Indies", "RPG", "Accion"], 'https://store.steampowered.com/app/237930/Transistor/', 'transistor.jpg', 'Transistor, de los creadores de Bastion, es un juego de rol con tematica de ciencia ficcion que te invita a blandir un arma extraordinaria de origen desconocido para luchar a lo largo y ancho de una espectacular ciudad futurista. En el  mismo se utiliza mucho las tematicas de la programacion para los mecanismos de combates').
juego('Spore', ["Sandbox", "Simulacion", "Exploracion"], 'https://store.steampowered.com/app/17390/SPORE/', 'spore.jpg', 'Spore es un videojuego de simulacion de vida y estrategia para Apple Macintosh y Microsoft Windows desarrollado por Maxis y disenado por Will Wright que simula la evolucion de una especie desde las etapas  mas primitivas es decir seres unicelulares, hasta la colonizacion de la galaxia por parte del ser evolucionado.').
juego('Darkest Dungeon', ["RPG", "Rogue Like", "Por Turnos"], 'https://store.steampowered.com/app/262060/Darkest_Dungeon/', 'darkestdungeon.jpg', 'Darkest Dungeon es un desafiante juego de rol gotico en mazmorras y por turnos que gira en torno al esfuerzo psicologico de la aventura. Recluta, entrena y lidera a un equipo de heroes imperfectos a traves  de enrevesados bosques, laberintos olvidados, criptas en ruinas y mas alla.').
juego('Wizard Legend', ["Rogue Like", "Indies", "Bullet Hell"], 'https://store.steampowered.com/app/445980/Wizard_of_Legend/', 'wizzardoflegends.jpg', 'Wizard of Legend es un juego de mazmorras vertiginoso que pone el acento en los combates magicos dinamicos. Los rapidos movimientos y uso de la magia aun mas rapido te permitiran encadenar hechizos para realizar  combinaciones devastadoras contra tus enemigos.').
juego('Forager', ["Indies", "Sandbox", "Casuales"], 'https://store.steampowered.com/app/751780/Forager/', 'forager.jpg', 'Forager es un videojuego de accion, exploracion, artesania y agricultura, mas una pizca de combate. Encarnaremos a un simpatico un personaje que esta en una isla solitaria, acompanados de un pico, algunos arboles y rocas, y que gracias a  su ingenio, debera sobrevivir y seguir adelante. Ademas es argentino papa.').
juego('Furi', ["Bullet Hell", "Accion", "Ciencia Ficcion"], 'https://store.steampowered.com/app/423230/Furi/', 'furi.jpg', 'Furi es un juego de accion beatem up que nos propone acabar con la vida de un variado grupo de enemigos finales. El juego apuesta por un sistema de combate inspirado por los clasicos japoneses. Utiliza la mecanica de solo combates contra jefes y buscar tener una dificultad elevada.').
juego('Planet Zoo', ["Simulacion", "Gestion", "Construccion"], 'https://store.steampowered.com/app/703080/Planet_Zoo/', 'planetzoo.jpg', 'Ambientandose en un enorme zoo, los jugadores tendran que gestionar pequenos ecosistemas para cada una de las especies de animales dentro del parque, mejorandolos poco a poco modificando el terreno y anadiendo juguetes y  atracciones para que los animales se diviertan y aprendan.').
juego('Pyre', ["Indies", "Deportes", "RPG"], 'https://store.steampowered.com/app/462770/Pyre/', 'pyre.jpg', 'Pyre es un RPG por equipos en el que intentaras conducir a la libertad a una banda de exiliados alcanzando la victoria en las ancestrales competiciones que se libran en un vasto y mistico purgatorio. Quien regresara entre laureles y quien pasara el  resto de sus dias condenado al exilio?').
juego('Children of Morta', ["Rogue Like", "Accion", "Indies"], 'https://store.steampowered.com/app/330020/Children_of_Morta/', 'childrenofmorta.jpg', 'Children of Morta es un juego de rpg de accion historial sobre una familia extraordinaria de heroes. Dirige a los Bergson, con todos sus defectos y virtudes, contra la proxima corrupcion. Seras capaz de sacrificar todo para salvar a los que te importan?').
juego('Graveyard Keeper', ["Indies", "Sandbox", "Gestion"], 'https://store.steampowered.com/app/599140/Graveyard_Keeper/', 'graveyard.jpg', 'Graveyard Keeper es el simulador de gestion de cementerios medievales mas impreciso de la historia. Construye y gestiona tu propio cementerio mientras encuentras formas de reducir costes, meterte en otras empresas y usar todos los recursos que encuentres.').
juego('Hand of Fate 2', ["Cartas", "Rogue Like", "Indies"], 'https://store.steampowered.com/app/456670/Hand_of_Fate_2/', 'handoffate2.jpg', 'Hand Of Fate 2 es un juego de exploracion de mazmorras ambientado en un mundo de oscura fantasia. Domina un juego de mesa rebosante de vida en el que cada fase de la aventura se saca de una baraja de encuentros legendarios que tu te encargas de elegir.').
juego('Have a Nice Death', ["Rogue Like", "Plataformas", "Accion"], 'https://store.steampowered.com/app/1740720/Have_a_Nice_Death/', 'haveanicedeath.jpg', 'Have a Nice Death es un roguelike de accion en el que encarnas a una Parca saturada por el trabajo. Sus empleados estan echando por tierra tanto el equilibrio de las almas. Con el fin de recuperar el orden, tendras que servirte de tu guadana para demostrar a los empleados quien manda aqui.').
juego('Back to Bed', ["Puzles", "Indies", "Casuales"], 'https://store.steampowered.com/app/308040/Back_to_Bed/', 'backtobed.jpg', 'Back to Bed es un juego indie de rompecabezas en 3D ambientado en un mundo de suenos unico, hermoso y artistico, en el que guias al sonambulo Bob a la seguridad de su cama. Para lograr esto, debes tomar el control del guardian subconsciente de Bob llamado Subob.').
juego('Nioh', ["RPG", "Accion", "Aventura"], 'https://store.steampowered.com/app/485510/Nioh_Complete_Edition/', 'nioh.jpg', 'La aventura se ambienta en el Japon feudal y cuenta con la presencia de multitud de demonios y seres sobrenaturales del folclore de dicho pais. Su estilo de lucha y combate sera arido y dificil, invitando al jugador a prepararse concienzudamente en cada enfrentamiento.').
juego('Titan Souls', ["Indies", "Bullet Hell", "Pixelados"], 'https://store.steampowered.com/app/297130/Titan_Souls/', 'titansouls.jpeg', 'El objetivo consiste en derrotar a los veinte monstruos gigantes (veintiuno en modo dificil) conocidos como los Titanes, los cuales, al igual que el jugador, solo pueden recibir un golpe pero solo tienen una forma de ser derrotados.').
juego('Zoo Tycoon', ["Simulacion", "Gestion", "Construccion"], 'https://store.steampowered.com/app/613880/Zoo_Tycoon_Ultimate_Animal_Collection/', 'zootycoon.jpg', 'En Zoo Tycoon tenemos que crear y gestionar un zoo, asegurandonos de que los animales sean felices, teniendo cubiertas sus necesidades basicas, lo que atraera a visitantes al zoo, a los que tambien tendremos que tener contentos con una fauna variada, servicios basicos como cafeterias, tiendas de recuerdos, etc.').
juego('Super Meat Boy Forever', ["Plataformas", "Indies", "Pixelados"], 'https://store.steampowered.com/app/581660/Super_Meat_Boy_Forever/', 'supermeatboyforever.jpg', 'Super Meat Boy Forever es una nueva entrega del famoso titulo de plataformas y accion. En este juego, Meat Boy y Bandage Girl han tenido una hija, Nugget, pero sus pacificas vidas familiares se veran interrumpidas cuando el Dr. Fetus regrese para secuestrar a la pequena Nugget.').
juego('Super Meat Boy', ["Plataformas", "Indies", "Pixelados"], 'https://store.steampowered.com/app/40800/Super_Meat_Boy/', 'supermeatboy.jpg', 'Super Meat Boy es un juego de plataformas extremadamente dificil en el que juegas en la piel de un cubo de carne animado que intenta salvar a su novia (que esta hecha de vendajes) de un malvado feto en un tarro que viste de esmoquin.').
juego('The Witcher 3 Wild Hunt', ["RPG", "Accion", "Aventura"], 'https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/', 'thewitcher3.jpg', 'Es un juego de perspectiva en tercera persona, el jugador controla al protagonista Geralt de Rivia, un cazador de monstruos conocido como Lobo Blanco, es un brujo, el cual emprende un largo viaje a traves de Los reinos del norte.').
juego('Tetris', ["Puzle", "Habilidad", "Estrategia"], 'https://store.steampowered.com/app/1003590/Tetris_Effect_Connected/', 'tetris.jpg', 'El objetivo es hacer caer piezas e ir rellenando huecos para conseguir hacer lineas. Una vez creadas, desaparecen, y nos interesa hacerlo de cuatro en cuatro en vez de una en una por los puntos que hay implicados en ello. Si consigues una de cuatro, felicidades, acabas de hacer un Tetris.').
juego('The Elder Scrolls V Skyrim', ["RPG", "Accion", "Mundo Abierto"], 'https://store.steampowered.com/app/489830/The_Elder_Scrolls_V_Skyrim_Special_Edition/', 'skyrim.jpg', 'La historia de Skyrim se centra en los esfuerzos del personaje, Dovahkiin (sangre de dragon), para derrotar a Alduin, un dragon/dovah que, segun la profecia, destruira el mundo. La trama esta fechada doscientos anos despues de los sucesos de Oblivion y tiene lugar en la provincia ficticia de Skyrim.').
juego('Red Dead Redemption 2', ["Accion", "Aventura", "Mundo Abierto"], 'https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/', 'redreadredemption2.jpg', 'Despues de que un atraco en el pueblo de Blackwater sale muy mal, Arthur Morgan y la banda Van der Linde se ven obligados a huirse. Con agentes federales y los mejores cazarrecompensas persiguiendolos, la banda debe robar, atracar y luchar por el duro corazon de Estados Unidos para sobrevivir.').
juego('Grand Theft Auto V', ["Accion", "Mundo Abierto", "Aventura"], 'https://store.steampowered.com/app/271590/Grand_Theft_Auto_V/', 'gta5.jpg', 'Se trata de una aventura de accion de mundo abierto con multitud de misiones en la que encarnamos a tres personajes distintos: Trevor, Michael y Franklin. Ademas, cuenta con GTA Online, el modo multijugador en linea de GTA 5.').
juego('Halo Combat Evolved', ["ETR", "Estrategia", "Construccion De Bases"], 'https://store.steampowered.com/app/1064221/Halo_Combat_Evolved_Anniversary/', 'halocombatevolved.jpg', 'En esta guerra galactica el juego nos situa en una especie de asalto por parte del Pacto a una nave nodriza en la cual nuestro heroe, que se llama "Jefe Maestro", se prepara para el conflicto. El asalto finaliza con nuestro heroe en orbita hacia el mundo-anillo de Halo, donde tendra que salvaguardar la I.A.').
juego('Halo Wars Definitive Edition', ["Shooter", "Ciencia Ficcion", "Multijugador"], 'https://store.steampowered.com/app/459220/Halo_Wars_Definitive_Edition/', 'halowarsde.jpg', 'Halo Wars para Xbox One es un nuevo juego de estrategia en tiempo real basado en el universo Halo, continuacion directa del primer Halo Wars de Xbox 360. El titulo cuenta con dos bandos, los humanos de la UNSC y los Banished, una raza alienigena que sustituye al Covenant.').
juego('Halo The Master Chief Collection', ["Shooter", "Ciencia Ficcion", "Multijugador"], 'https://store.steampowered.com/app/976730/Halo_The_Master_Chief_Collection/', 'halotmce.jpg', 'Halo es una franquicia de videojuegos de ciencia ficcion creada y desarrollada por Bungie Studios hasta Halo Reach, y gestionada ahora por 343 Industries, propiedad de Xbox Game Studios. La serie se centra en una guerra interestelar entre la humanidad y una alianza teocratica de alienigenas conocidos como Covenant.').
juego('Portal 2', ["Puzle", "Plataformas", "Accion"], 'https://store.steampowered.com/app/620/Portal_2/', 'portal2.jpg', 'Tras los eventos del primer Portal, Chell (nuestra protagonista) despierta 50 dias despues de haber sido criogenizada en una camara de relajacion, donde una maquina alternativa le da una serie de indicaciones para moverse y finalmente volver a dormir.').
juego('Chrono Trigger', ["RPG", "Viaje en el Tiempo", "Aventura"], 'https://store.steampowered.com/app/613830/CHRONO_TRIGGER/', 'ChronoTrigger.jpg', 'La historia del juego sigue a un grupo de jovenes aventureros que fueron transportados a traves del tiempo accidentalmente y descubrieron que el mundo iba a ser destruido en un futuro lejano. Jurando prevenir este desastre, viajan a traves de distintas epocas para descubrir la forma de salvar al planeta.').
juego('Metal Gear Solid Master Collection Vol1', ["Accion", "Sigilo", "Narrativa"], 'https://store.steampowered.com/app/2131630/METAL_GEAR_SOLID_MASTER_COLLECTION_Vol1_METAL_GEAR_SOLID/', 'METALGEARSOLIDMASTERCOLLECTIONVol1METALGEAR SOLID.jpg', 'Metal Gear Solid es un videojuego de accion y sigilo firmado por Hideo Kojima y Konami para la consola PlayStation. Se trata de una secuela de Metal Gear y Metal Gear 2: Solid Snake. Descrito por su propio creador como "accion tactica de espionaje" en el titulo, la historia sigue la mision de Solid Snake, un soldado infiltrado en una instalacion de desarrollo de armas nucleares (Shadow Moses) para neutralizar un terrorista y salvar unos rehenes, entre ellos el jefe de DARPA.').
juego('Mass Effect', ["RPG", "Ciencia Ficcion", "Accion"], 'https://store.steampowered.com/app/17460/Mass_Effect_2007/', 'masseffect.jpg', 'Mass Effect es un videojuego de rol de accion y disparos en 3 persona de ciencia ficcion para Xbox 360, Microsoft Windows y posteriormente PlayStation 3, desarrollado por BioWare, famoso estudio desarrollador de juegos de rol como Jade Empire, Star Wars: Caballeros de la Antigua Republica.').
juego('Bloodborne', ["Accion", "RPG", "Fantasia Oscura"], 'No existe :c', 'bloodborn.jpg', 'Bloodborne nos lleva a la decrepita ciudad de Yharnam, cuyos habitantes han sido infectados por una misteriosa enfermedad sanguinea. Nosotros encarnamos al Cazador, un personaje que tendra que buscar una misteriosa sustancia llamada Sangre palida mientras resuelve misterios y se enfrenta a todo tipo de criaturas.').
juego('Half Life', ["Shooter", "Ciencia Ficcion", "Accion"], 'https://store.steampowered.com/app/70/HalfLife/', 'halflife.jpg', 'Half-Life narra las aventuras de Gordon Freeman, un cientifico teorico del Laboratorio de Materiales Anomalos del Centro de Investigacion Black Mesa, un enorme complejo cientifico subterraneo y ultra secreto instalado en una base militar en desuso emplazada en el desierto de Nuevo Mexico.').
juego('Half Life 2', ["Shooter", "Ciencia Ficcion", "Accion"], 'https://store.steampowered.com/app/220/HalfLife_2/', 'halflife2.jpg', 'Un shooter en primera persona que transcurre dos decadas despues de la historia del primer Half Life. Gordon Freeman despierta de su estado de hibernacion y se convierte en el simbolo de la resistencia humana frente a la Alianza. Accion en una aventura cuya historia profundiza mucho mas alla del conflicto.').
juego('Half Life Alyx', ["Shooter", "Ciencia Ficcion", "Accion"], 'https://store.steampowered.com/app/546560/HalfLife_Alyx/', 'halflifealyx.jpg', 'Es la historia de una lucha imposible contra una raza alienigena cruel conocida como la Alianza, situada entre los eventos de Half-Life y Half-Life 2. Jugando como Alyx Vance, eres la unica oportunidad de supervivencia de la humanidad.').
juego('Overwatch 2', ["Shooter", "Multijugador", "Accion"], 'https://store.steampowered.com/app/2357570/Overwatch_2/', 'overwatch2.jpeg', 'Overwatch 2 es un juego gratuito de accion y disparos en equipos a cargo de Blizzard para PC, PlayStation 4, Xbox One, PlayStation 5, Xbox Series y Switch siempre activo y en constante evolucion que esta ambientado en un futuro optimista, donde en cada partida se viven intensas batallas de 5 vs. 5.').
juego('Diablo II', ["RPG", "Accion", "Fantasia"], 'https://diablo2.blizzard.com/es-es/', 'Diablo2.jpg', 'Diablo II: Resurrected es una version remasterizada del gran clasico de rol y accion Diablo II. Persigue al misterioso vagabundo oscuro y lucha contra los moradores del infierno mientras investigas el destino de los demonios mayores, Diablo, Mefisto y Baal, ahora hasta en 4K (2160p) en PC.').
juego('Resident Evil 3', ["Survival Horror", "Accion", "Zombis"], 'https://store.steampowered.com/app/952060/Resident_Evil_3/', 're3.png', 'El 28 de septiembre de 1998, la exmiembro del Servicio Especial de Tacticas y Rescate (S.T.A.R.S.), Jill Valentine, es atacada en su departamento por una arma biologica inteligente conocida como Nemesis, que intenta matarla a ella y a todos los miembros restantes de S.T.A.R.S.').
juego('Resident Evil 4', ["Survival Horror", "Accion", "Zombis"], 'https://store.steampowered.com/app/2050650/Resident_Evil_4/', 're4.jpeg', 'Sigue la historia del sobreviviente Leon Scott Kennedy, ahora un agente de Estados Unidos al cual se le asigno la mision de rescatar a la hija del actual presidente del pais, Ashley Graham, quien habia sido raptada por un grupo terrorista desconocido.').
juego('Resident Evil 7', ["Survival Horror", "Accion", "Terror"], 'https://store.steampowered.com/app/418370/Resident_Evil_7_Biohazard/', 're7.jpg', 'La historia gira alrededor de Ethan, el protagonista de la trama que decide ir a buscar a su desaparecida pareja, Mia, de la que no sabe nada desde hace mas de tres anos. Un misterioso correo electronico firmado a su nombre le indica la llegada a una casa regentada por la familia Baker.').
juego('Fallout New Vegas', ["RPG", "Mundo Abierto", "Accion"], 'https://store.steampowered.com/app/22380/Fallout_New_Vegas/', 'falloutnw.jpg', 'Fallout: New Vegas es un juego de rol de accion ambientado en un mundo postapocaliptico en el ano 2281. El jugador asume el papel de un mensajero que es dejado moribundo en el desierto de Mojave despues de ser atacado y robado de un paquete muy valioso.').
juego('The Last of Us', ["Accion", "Aventura", "Supervivencia"], 'https://store.steampowered.com/app/1888930/The_Last_of_Us_Parte_I/', 'thelastofus.jpg', 'La trama describe las vivencias de Joel y Ellie, un par de supervivientes de una pandemia en Estados Unidos que provoca la mutacion de los seres humanos en criaturas canibales.').
juego('StarCraft', ["Estrategia en Tiempo Real", "Ciencia Ficcion", "Multijugador"], 'https://us.shop.battle.net/es-es/product/starcraft-remastered', 'starcraft.jpg', 'Comanda a los mecanizados terran, los psionicos protoss y los insectoides zerg en grandes batallas por el control de mapas en ocho entornos unicos. Construye tu base y recluta un ejercito en este juego de guerra en tiempo real ambientado en un futuro de ciencia ficcion.').
juego('OneShot', ["Pixelados", "Puzle", "Elecciones"], 'https://store.steampowered.com/app/420530/OneShot/', 'OneShot.png', 'OneShot es un juego de aventuras y rompecabezas surrealista con perspectiva a vista de pajaro y una jugabilidad unica. Tienes que guiar a un nino a traves de un misterioso mundo en una mision para recuperar su sol, que murio hace mucho tiempo. El mundo sabe que existes.').
juego('Monument Valley', ["Aventura", "Puzle", "Casuales"], 'https://store.steampowered.com/app/1927720/Monument_Valley_Panoramic_Edition/', 'monument.jpg', 'En Monument Valley, debes manipular arquitecturas imposibles y guiar a una princesa silenciosa por un mundo de belleza incomparable. Monument Valley es un viaje irreal por construcciones fantasticas y geometrias imposibles.').
juego('Left 4 Dead 2', ["Zombies", "Shooter", "Multijugador"], 'https://store.steampowered.com/app/550/Left_4_Dead_2/', 'l4d2.jpg', 'Left 4 Dead 2 se desarrolla tres semanas despues del primer brote viral que se ha expandido en el sur de los Estados Unidos, infectando los territorios entre Georgia y Luisiana. La infeccion ya ha cobrado las vidas de millones de personas y sus mutaciones extraordinarias siguen apareciendo.').
juego('Hollow Knight', ["Metroidvaina", "Plataformas", "Accion"], 'https://store.steampowered.com/app/367520/Hollow_Knight/', 'hollowknight.jpg', 'Hollow Knight es una aventura de accion clasica en 2D ambientada en un vasto mundo interconectado. Explora cavernas tortuosas, ciudades antiguas y paramos mortales. Combate contra criaturas corrompidas, haz nuevas amistades con extranos insectos y resuelve los antiguos misterios que yacen en el corazon del reino.').
juego('Slay the Spire', ["Rogue Like", "Cartas", "Estrategia"], 'https://store.steampowered.com/app/646570/Slay_the_Spire/', 'slayofspire.jpg', 'Hemos fusionado juegos de cartas y roguelikes para crear el mejor juego de cartas para un solo jugador que pudieramos. Crea un mazo unico, encuentra criaturas extranas, descubre reliquias de inmenso poder y mata La Aguja.').
juego('Slime Rancher', ["Aventura", "Gestion", "Casuales"], 'https://store.steampowered.com/app/433340/Slime_Rancher/', 'slimerancher.jpg', 'Juega como Beatrix LeBeau: una intrepida joven ranchera que se aventura a una vida a mil anos luz de la Tierra en la Lejana, Lejana Pradera. Cada dia presenta nuevos retos y riesgosas oportunidades mientras intentas amasar una gran fortuna en el negocio de la crianza de slimes.').
juego('Papers Please', ["Indie", "Simulacion", "Elecciones"], 'https://store.steampowered.com/app/239030/Papers_Please/', 'pappersplease.jpg', 'Papers, Please tiene lugar en 1982 despues de una guerra de seis anos entre los estados ficticios de Arstotzka y Kolechia. La mecanica del juego se enfoca en la vida laboral de un inspector de inmigracion que trabaja para el gobierno de Arstotzka en un control fronterizo ubicado entre Arstotzka y Kolechia.').
juego('Cookie Clicker', ["Indie", "Clicker", "Casuales"], 'https://store.steampowered.com/app/1454400/Cookie_Clicker/', 'CookieClicker.png', 'Cookie Clicker es un emocionante juego de hacer clic que te da la bienvenida a un mundo cautivador. En este juego, tu objetivo final es reclamar el titulo de Cookie King, gobernando un reino de delicias deliciosas.').
juego('Kingdom Rush', ["Indie", "Construccion De Bases", "Estrategia"], 'https://store.steampowered.com/app/246420/Kingdom_Rush___Tower_Defense/', 'kingdomrush.jpg', 'De que se trata? El reino esta bajo ataque. En Kingdom Rush debes defender tu reino contra hordas de trolls, orcos, demonios desagradables y trolls. Enfrentate a ellos con un grupo de guerreros y magos que defenderan su reino hasta el final.').
juego('Cuphead', ["Plataformas", "Indie", "Accion"], 'https://store.steampowered.com/app/268910/Cuphead/', 'Cuphead.jpg', 'Cuphead es un juego clasico de accion de disparos muy enfocado en batallas de jefes. Inspirado en las caricaturas de 1930, las imagenes y el audio se crearon de forma minuciosa con las mismas tecnicas de la era, esto es, animacion tradicional a mano, fondos de marca de agua y grabaciones originales de jazz.').
juego('God of War', ["Accion", "Aventura", "RPG"], 'https://store.steampowered.com/app/1593500/God_of_War/', 'GodofWar.jpg', 'Tras haberse cobrado su venganza contra su padre Zeus y los demas Dioses Olimpicos, el antiguo dios de la guerra, Kratos, ahora vive con su joven hijo Atreus en el mundo de los Dioses Nordicos, una tierra hostil habitada por feroces monstruos y guerreros.').
juego('The Forest', ["Supervivencia", "Terror", "Accion"], 'https://store.steampowered.com/app/242760/The_Forest/', 'TheForest.jpg', 'En The Forest asumimos el papel de Eric Leblanc, padre que viaja junto a su hijo (Timmy Leblanc) en un avion. En mitad del vuelo sufrimos un terrible accidente en una peninsula remota y, aunque logramos sobrevivir al devastador impacto, presenciamos el secuestro de nuestro hijo.').
juego('DOOM', ["Shooter", "Accion", "Clasico"], 'https://store.steampowered.com/app/379720/DOOM/', 'DOOM.jpg', 'Los jugadores toman el papel de un marine espacial sin nombre mientras lucha contra las fuerzas demoniacas del infierno que han sido desatadas por la Union Aerospace Corporation en un planeta colonizado en el futuro, Marte.').
juego('Outer Wilds', ["Exploracion", "Aventura", "Puzle"], 'https://store.steampowered.com/app/753640/Outer_Wilds/', 'OuterWilds.jpg', 'Outer Wilds es un videojuego de mundo abierto en el que podemos vivir una aventura de misterio en un sistema solar que ha quedado atrapado en un bucle temporal. El usuario debe explorar este mundo en primera persona para descubrir el secreto arcano que se esconde tras este misterio.').
juego('Amnesia The Dark Descent', ["Terror", "Supervivencia", "Puzle"], 'https://store.steampowered.com/app/57300/Amnesia_The_Dark_Descent/', 'AmnesiaTheDarkDescent.jpg', 'El juego se desarrolla en el ano 1839, y el jugador toma el papel de Daniel, un joven de Londres que despierta en los oscuros pasillos del Castillo Brennenburg con poca memoria de si mismo y de su pasado. Todo lo que puede recordar es su nombre, que vive en Mayfair y que algo lo esta cazando.').
juego('Untitled Goose Game', ["Casuales", "Indie", "Divertido"], 'https://store.steampowered.com/app/837470/Untitled_Goose_Game/', 'UntitledGooseGame.jpg', 'Ubicado en un pueblo ingles de clase media, en Untitled Goose Game los jugadores controlan un ganso mientras usan su habilidad para graznar, batir sus alas y agarrar objetos con su pico para molestar a varios aldeanos humanos.').
juego('Coffee Talk', ["Conversacion", "Pixelados", "Indie"], 'https://store.steampowered.com/app/914800/Coffee_Talk/', 'CoffeeTalk.jpg', 'es un titulo que nos pone en la piel de un barista (profesional especializado en servir cafe de gran calidad) en un Seattle actual, pero que a la vez tiene un punto de futurista, fantastico y cyberpunk, porque cuenta con enanos, elfos y orcos trabajando en distintos empleos relacionados con las tecnologias.').
juego('Plague Inc Evolved', ["Estrategia", "Simulacion", "Indie"], 'https://store.steampowered.com/app/246620/Plague_Inc_Evolved/', 'plagueinc.jpg', 'Es una mezcla unica de estrategia y simulacion terrorificamente realista. Tu patogeno acaba de infectar al paciente cero. Ahora tu mision es extinguir a la humanidad propagando una epidemia letal mientras saboteas los esfuerzos de la poblacion para combatirla.').
juego('Elden Ring', ["Accion", "RPG", "Fantasia Oscura"], 'https://store.steampowered.com/app/1245620/ELDEN_RING/', 'EldenRing.jpg', 'Elden Ring tiene lugar en las Tierras Intermedias, un continente ficticio gobernado por diferentes semidioses. Anteriormente estaba gobernado por la Reina Marika la Eterna, la cual actuaba como guardiana del Circulo de Elden, una poderosa fuerza que se manifiesta como el concepto fisico del orden').
juego('Thymesia', ["Accion", "RPG", "Fantasia Oscura"], 'https://store.steampowered.com/app/1343240/Thymesia/', 'Thymesia.jpeg', 'Thymesia es un arduo RPG de accion con un combate rapido y un complejo sistema de plagas como armas. En un reino donde la muerte campa a sus anchas, jugaras con el misterioso personaje Corvus. Da caza a tus enemigos, blande el poder de la enfermedad y encuentra la verdad en tus propios recuerdos.').
juego('The Mageseeker', ["RPG", "Pixelados", "Accion"], 'https://store.steampowered.com/app/1457080/The_Mageseeker_A_League_of_Legends_Story/', 'TheMageseeker.jpg', 'Juega como Sylas, un mago robahechizos que acaba de liberarse de un aprisionamiento injusto a manos de los cazadores de magos. Tendras que empunar las cadenas que en algun momento te retuvieron para liberar tus tierras de la tirania, eliminando a los cazadores de magos uno por uno.').
juego('South Park The Fractured But Whole', ["RPG", "Divertido", "Accion"], 'https://store.steampowered.com/app/488790/South_Park_The_Fractured_But_Whole/', 'southparkfractured.jpg', 'La narrativa del juego ocurre un dia despues de los eventos de su predecesor; sigue al Nino Nuevo, quien se ha mudado recientemente a South Park y se involucra en un epico juego de rol que implica a dos facciones rivales de superheroes compitiendo por crear sus propias franquicias mediaticas de superheroes.').
juego('Baldurs Gate 3', ["RPG", "Elecciones", "Sigilo"], 'https://store.steampowered.com/app/1086940/Baldurs_Gate_3/', 'baldure.jpg', 'Reune a tu grupo y vuelve a los Reinos Olvidados en un relato de companerismo y traicion, sacrificio y supervivencia, ademas de la atraccion de un poder absoluto.').
juego('Starfield', ["RPG", "Mundo Abierto", "Ciencia Ficcion"], 'https://store.steampowered.com/app/1716740/Starfield/', 'starfield.jpg', 'Starfield es el primer universo nuevo en 25 anos de Bethesda Game Studios, los galardonados creadores de The Elder Scrolls V: Skyrim y Fallout 4.').
juego('Cyberpunk 2077', ["RPG", "Mundo Abierto", "CiberPunk"], 'https://store.steampowered.com/app/1091500/Cyberpunk_2077/', 'ciberpunk.jpg', 'Cyberpunk 2077 es un RPG de aventura y accion de mundo abierto ambientado en el futuro sombrio de Night City, una peligrosa megalopolis obsesionada con el poder, el glamur y las incesantes modificaciones corporales.').
juego('Remnant II', ["Accion", "Aventura", "RPG"], 'https://store.steampowered.com/app/1282100/Remnant_II/', 'remant2.jpg', 'Remnant II es la secuela del juego superventas Remnant: From the Ashes que enfrenta a los supervivientes de la humanidad contra nuevas criaturas mortiferas y jefes divinos en mundos aterradores.').
juego('Fae Farm', ["Simulacion", "Gestion", "Casuales"], 'https://store.steampowered.com/app/2230110/Fae_Farm/', 'FaeFarm.jpg', 'Escapa al cuento de hadas con el que siempre ha sonado en Fae Farm. un juego de rol y simulacion para hasta 4 personas. Crea, cultiva y decora tu finca, y usa hechizos para explorar la encantadora isla Azoria. Forjaras nuevos lazos con los islenos y descubrira la magia de las hadas.').
juego('Divinity Original Sin 2', ["Estrategia", "Por Turnos", "RPG"], 'https://store.steampowered.com/app/435150/Divinity_Original_Sin_2__Definitive_Edition/', 'divinity2.jpg', 'The critically acclaimed RPG that raised the bar, from the creators of Baldur\'s Gate 3. Gather your party. Master deep, tactical combat. Venture as a party of up to four - but know that only one of you will have the chance to become a God.').
juego('Sea of Stars', ["RPG", "Por Turnos", "Pixelados"], 'https://store.steampowered.com/app/1244090/Sea_of_Stars/', 'seastars.jepg', 'Sea of Stars is a turn-based RPG inspired by the classics. It tells the story of two Children of the Solstice who will combine the powers of the sun and moon to perform Eclipse Magic, the only force capable of fending off the monstrous creations of the evil alchemist known as The Fleshmancer.').
juego('Hogwarts Legacy', ["Fantasia", "Mundo Abierto", "Magia"], 'https://store.steampowered.com/app/990080/Hogwarts_Legacy/', 'hogwarts.jpg', 'Hogwarts Legacy es un RPG inmersivo de accion en mundo abierto. Ahora puedes tomar el control de la accion y ser el centro de tu propia aventura en el mundo magico.').
juego('Fallout 76', ["RPG", "Mundo Abierto", "Multijugador"], 'https://store.steampowered.com/app/1151340/Fallout_76/', 'Fallout76.jpeg', 'Bethesda Game Studios te da la bienvenida a Fallout 76. Veinticinco anos despues de la caida de las bombas, saldras junto a los demas companeros moradores del refugio a la America posnuclear. Explora un amplio Yermo en este juego multijugador de mundo abierto que completa la historia de Fallout.').
juego('SCUM', ["Supervivencia", "Zombis", "Multijugador"], 'https://store.steampowered.com/app/513710/SCUM/', 'scum.jpg', 'SCUM aims to evolve the multiplayer open world survival game with unprecedented levels of character customization, control and progression, where knowledge and skills are the ultimate weapons for long-term survival.').
juego('Mortal Kombat 1', ["Lucha", "Accion", "Clasico"], 'https://store.steampowered.com/app/1971870/Mortal_Kombat_1/', 'mortalkombat1.jpg', 'Descubre un nuevo universo de Mortal Kombat creado por Liu Kang, Dios del Fuego. Mortal Kombat 1 abre paso a una nueva era de esta iconica saga con un nuevo sistema de kombate, modos de juego y fatalities!').
juego('ONE PIECE PIRATE WARRIORS 4', ["Lucha", "Accion", "Anime"], 'https://store.steampowered.com/app/1089090/ONE_PIECE_PIRATE_WARRIORS_4/', 'onepiecepw4.jpg', 'ONE PIECE: PIRATE WARRIORS 4 pone al dia la accion de PIRATE WARRIORS! Inspirado en el concepto de experimentar un campo de batalla real de ONE PIECE, los edificios se derrumbaran durante los combates y los ataques generaran humo y polvo, para que disfrutes como nunca del mundo de ONE PIECE.').
juego('STAR WARS Jedi Fallen Order', ["Accion", "RPG", "Ciencia Ficcion"], 'https://store.steampowered.com/app/1172380/STAR_WARS_Jedi_La_Orden_cada/', 'starwrscolorado1.jpg', 'Una aventura de dimensiones galacticas te espera en Star Wars Jedi: Fallen Order, un juego de aventuras y accion en tercera persona de Respawn Entertainment. Este titulo para un jugador centrado en la historia te pone en la piel de un padawan Jedi que ha escapado a duras penas de la purga de la Orden 66 despues del Episodio III: La venganza de los Sith. Para reconstruir la Orden Jedi, deberas reunir los fragmentos de tu pasado para completar tu entrenamiento, desarrollar nuevas y poderosas habilidades con la Fuerza y dominar la espada laser antes de que el Imperio y sus mortiferos inquisidores te alcancen.').
juego('TEKKEN 8', ["Lucha", "Accion", "Clasico"], 'https://store.steampowered.com/app/1778820/TEKKEN_8/', 'tekken8.png', 'Preparate para el proximo capitulo de la legendaria franquicia del juego de lucha: TEKKEN 8.').
juego('ONE PUNCH MAN A HERO NOBODY KNOWS', ["Accion", "Lucha", "Anime"], 'https://store.steampowered.com/app/991560/ONE_PUNCH_MAN_A_HERO_NOBODY_KNOWS/', 'onepunch.jpg', 'Sumergente en un juego de lucha dinamico con los famosos personajes de One Punch Man! Haz de tu heroe preferido o conviertete tu en uno!').
juego('Mortal Kombat X', ["Lucha", "Accion", "Clasico"], 'https://store.steampowered.com/app/307780/Mortal_Kombat_X/', 'mkx.jpg', 'Disfruta de la nueva generacion de la franquicia de lucha n. 1. Mortal Kombat X reune un aspecto cinematografico y una mecanica de juego nunca vistos.').
juego('DAVE THE DIVER', ["Gestion", "Casuales", "Pixelados"], 'https://store.steampowered.com/app/1868140/DAVE_THE_DIVER/', '4', 'DAVE THE DIVER es un juego casual de rol y aventuras para un solo jugador que incluye elementos de pesca y exploracion del fondo marino durante el dia y de gestion de un restaurante de sushi durante la noche. Ayuda a Dave y a sus extranos amigos a destapar los secretos de la misteriosa Fosa Azul.').
juego('Football Manager 2023', ["Simulacion", "Deportes", "Gestion"], 'https://store.steampowered.com/app/1904540/Football_Manager_2023/', 'fm23.jpg', 'Confecciona la plantilla de tus suenos, supera a tus rivales y vive la emocion de las grandes noches europeas en la UEFA Champions League. Emprende tu viaje hacia la gloria.').
juego('Farming Simulator 22', ["Simulacion", "Gestion", "Casual"], 'https://store.steampowered.com/app/1248130/Farming_Simulator_22/', 'fs22.jpg', 'Crea tu propia granja y cosecha diversion! Siembra cultivos, cuida de los animales, gestiona la produccion y enfrentate al desafio de las estaciones.').
juego('Digimon World Next Order', ["Coleccion de Criaturas", "RPG", "Anime"], 'https://store.steampowered.com/app/1530160/Digimon_World_Next_Order/', 'DigimonWorldNO.jpg', 'El Mundo Digital ha sido asaltado por Machinedramon y ahora esta en el caos mas absoluto. Como un Digidestinado, debes restaurar el orden en el mundo en Digimon World: Next Order, un RPG de coleccionar monstruos.').
juego('Monster Hunter Stories 2 Wings of Ruin', ["Coleccion de Criaturas", "RPG", "Aventura"], 'https://store.steampowered.com/app/1277400/Monster_Hunter_Stories_2_Wings_of_Ruin/', 'MOSTERHUNTERS2.jpg', 'Nueva aventura en la segunda entrega de esta serie de juegos de rol por turnos ambientada en el mundo de Monster Hunter! Conviertete en un Rider y unete a monstruos amistosos (los llamados Monsties) parar luchar a su lado embarcandote en una historia epica.').
juego('Flutter Away', ["Casual", "Coleccion de Criaturas", "Exploracion"], 'https://store.steampowered.com/app/2224030/Flutter_Away/', 'carpincho.jpg', 'Disfruta de la serenidad de la selva amazonica en este breve juego de exploracion de la naturaleza tan agradable. Como investigador de mariposas en un viaje de cinco dias, explora los senderos cercanos, saca fotografias, conoce animales amistosos y de paso documenta tus descubrimientos!').


recuperar_categorias(Juego, Categorias) :-
    juego(Juego, Categorias, _, _, _).

%con findall busca todos los juegos que cumplen que Lista sea sublista de Categoria con el forall y el member, y esos juegos los guarda en Resultado. 
recuperar_juegos_con_categorias(Lista, Resultado) :-
    findall(Juego, (
        juego(Juego, Categorias, _, _, _),
        forall(member(Categoria, Lista), member(Categoria, Categorias))
    ), Resultado).

recuperar_imagen(Juego, Imagen) :-
    juego(Juego, _, _, Imagen, _).

recuperar_link(Juego, Link) :-
    juego(Juego, _, Link, _, _).

recuperar_sinopsis(Juego, Sinopsis) :-
    juego(Juego, _, _, _, Sinopsis).